Tunikov.dmitrii
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #10
Opened 2019-10-14 18:56 UTC by DmitriiTunikov

2019-10-14 18:59 UTC, DmitriiTunikov commented
@SWAGLORD1 Здравсвуйте, удалил файлы, оставшиеся после сборки через idea.

2019-10-15 22:09 UTC, KotsMikhail requested changes
Когда я просил оставить только код и скрипт для сборки, я имел в виду, что все остальное из ветки нужно убрать, включая ридми и файлы заданий, иначе, когда я солью вашу ветку с мастером, возникнет куча конфликтов. Не создавайте новый pull request, просто сделайте ещё один коммит.
Запустил демона со следующим конфигом:
watch_directories:/Documents/OS_Labs_SPBPU_2019/tunikov.dmitrii/lab1
pid_file:/var/run/daemon.pid
Программа упала с ошибкой *** Error in `./inotify': double free or corruption (top): 0x0000000000f0a210 ***
В целом, задавать расположение pid файла в конфиге - не лучшая идея. Стандартное решение - располагать его в /var/run, если очень хотите, чтобы его положение было настраиваемым - сделайте его параметром сборки
Скрипт build.sh должен очищать промежуточные файлы сборки и оставлять только исполняемый файл.

2019-10-21 08:13 UTC, DmitriiTunikov commented
@SWAGLORD1 Удалил файлы сборки и readme и тд. 
Сделал имя пид файла вторым аргументов программы.

2019-10-22 00:38 UTC, KotsMikhail requested changes
Запустил демона следующей командой:
./build/inotify inotify.cfg daemon.pid
Программа упала со следующим выходом:
parent hereHello from child with pid = 2626 and ppid = 1
*** Error in `./build/inotify': double free or corruption (top): 0x00000000009687a0 ***
Оба файла в аргументах существуют и не пустые

2019-10-22 16:16 UTC, DmitriiTunikov commented
@SWAGLORD1 Я поправил демона. Почему у вас вылетает с такой ошибкой - не знаю. Попробуйте сейчас запустить, я глобальные правки достаточно сделал.
У меня корректно такая последовательность действий отрабатывает. 
Кстати, можете передавать абсолютный путь к конфиг файлу? Просто иначе при перечтении конфига демон не может найти конфиг файл.

2019-10-24 11:42 UTC, KotsMikhail requested changes
Вызвал скрипт сборки командой sudo ./build.sh
Получил ошибку:
touch: cannot touch '': No such file or directory
can't touch pid_file: 0

2019-10-24 15:04 UTC, DmitriiTunikov commented
@SWAGLORD1 Да. Потому что я сделал pid_file_name параметром сборки.Можете в скрипте посмотреть

2019-10-24 20:19 UTC, KotsMikhail requested changes
Тогда у этого параметра должно быть дефолтное значение, или вызов конфига без параметров должен выводить help. Или пользователь должен догадаться, как установить вашу программу?

2019-10-25 08:49 UTC, DmitriiTunikov commented
@SWAGLORD1 вывожу сообщение об ошибке, при отсуствии pid_file_name, как аргумента build.sh

2019-10-26 17:03 UTC, KotsMikhail requested changes
Запустил скрипт установки командой sudo ./build.sh /var/run/daemon.pid
Получил ошибку c++: error: PID_FILE_NAME=/var/run/daemon.pid: No such file or directory
У меня стоит cmake 3.15.4

2019-10-26 19:29 UTC, DmitriiTunikov commented
@SWAGLORD1 У меня стоит cmake 3.12.4 (такая версия необходима для использования опции add_compile_defenition). И я проверял на двух компах, все работает корректно.
Такой ошибки в принципе не может быть, если PID_FILE_NAME был создан в скрипте, а он точно был создан(в скрипте стоит проверка на это, да и он вывелся у вас).
Нет понимания, как такое может быть.
Попробуйте запустить sudo bash build.sh /var/run/daemon.pid 
Знаю, что разницы по идее не будет, но мне просто ОС не дает запускать так, как вы запустили (через ./)

Попробовал перенести build.sh в папку с проектом. Может это поможет в вашем случае. Не знаю.
Если не выйдет запустить. Я могу, конечно, логику с pid_file переделать. Убрать настройку через build скрипт. Оставить просто хардкод.

2019-10-26 21:11 UTC, KotsMikhail requested changes
Программа установилась и вроде работает, но далеко не все события, которые возвращает inotify обрабатываются. Я увидел только создание и изменение, что насчет остальных? В коде вроде ещё есть удаление, но сообщения, связанные с ним у меня в логе не появляются
Так же ваша программа выводит кучу лишней отладочной информации, которой не должно быть в релизе

2019-10-26 21:11 UTC, KotsMikhail commented on tunikov.dmitrii/lab1/core/ConfigHolder.h
> +    ConfigHolder();
Когда пишете синглтон, оператор и конструктор копирования тоже лучше приватить или удалять с помощью = delete

2019-10-26 21:11 UTC, KotsMikhail commented on tunikov.dmitrii/lab1/core/Exception.hpp
> +class CommonException : public std::exception
Чем вас std::runtime_error не устраивает?

2019-10-26 21:11 UTC, KotsMikhail commented on tunikov.dmitrii/lab1/core/inotify.hpp
> +#define BUF_LEN     ( MAX_EVENTS * ( EVENT_SIZE + LEN_NAME ))
Задавать константы дефайнами - плохой стиль, используйте static const поля

2019-10-26 21:11 UTC, KotsMikhail commented on tunikov.dmitrii/lab1/main.cpp
> +#define BUF_LEN     ( MAX_EVENTS * ( EVENT_SIZE + LEN_NAME ))
Повторное объявление констант

2019-10-26 21:11 UTC, KotsMikhail commented on tunikov.dmitrii/lab1/main.cpp
> +static inotifier* inotifier;
Почему эти переменные должны быть глобальными?

2019-10-26 21:11 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab1/core/utils.hpp
> +                if (stat(path_to_old_pid.c_str(), &sb) == 0)
Что будет, если послать сигнал несуществующему процессу?

2019-10-26 22:06 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab1/core/Exception.hpp
> +class CommonException : public std::exception
Не знал про такой. Но думаю это не проблема - использовать свой кастомный класс для Exception.

2019-10-26 22:07 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab1/core/utils.hpp
> +                if (stat(path_to_old_pid.c_str(), &sb) == 0)
Не понял вопрос. При посылке сигнала несуществующему процессу мое приложение никак на это не отреагирует.

2019-10-26 22:09 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab1/main.cpp
> +#define BUF_LEN     ( MAX_EVENTS * ( EVENT_SIZE + LEN_NAME ))
Потому что я использую их в разных функциях в файле main.cpp
В функции close() удаляю notifier
В функции signalHandle использую cfgFile

2019-10-26 23:05 UTC, DmitriiTunikov commented
@SWAGLORD1 
Исправил все замечания.
Не понял замечание про сигнал другому процессу (причем тут мой процесс не понял).
Остальное исправил.

2019-10-27 09:34 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab1/core/ConfigHolder.h
> +    ConfigHolder();
Сделал

2019-10-27 09:34 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab1/core/inotify.hpp
> +#define BUF_LEN     ( MAX_EVENTS * ( EVENT_SIZE + LEN_NAME ))
Сделал

2019-10-27 09:35 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab1/main.cpp
> +static inotifier* inotifier;
Потому что я использую их в разных функциях в файле main.cpp
В функции close() удаляю notifier
В функции signalHandle использую cfgFile.

2019-10-27 09:35 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab1/main.cpp
> +#define BUF_LEN     ( MAX_EVENTS * ( EVENT_SIZE + LEN_NAME ))
Удалил

2019-10-27 09:37 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab1/core/ConfigHolder.h
> +    ConfigHolder();
Добавил все сообщения, которые может inotify отслеживать.

2019-10-27 16:57 UTC, KotsMikhail approved these changes
Засчитано. По поводу кастомного exception - это не большая проблема, но лучше все таки не лепить велосипеды, а использовать существующие решения, когда они есть

2019-10-27 16:57 UTC, merged