Add daemon
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #11
Opened 2019-10-21 09:51 UTC by Ppasha9

- "first" final version of daemon

2019-10-22 01:32 UTC, KotsMikhail requested changes
В целом неплохо, кроме небольших замечаний по коду
Логирование стоит настроить с помощью openlog, чтобы в лог выводился хотя бы pid процесса
Так же демон не должен спамить в лог кучу сообщений каждые 30 секунд, это удобно для отладки, но не очень удобно для пользователя

2019-10-22 01:32 UTC, SWAGLORD1 commented on denisov.pavel/lab1/common.h
> +#define INFO(...)    do{ syslog(   LOG_INFO, ##__VA_ARGS__); } while(0)
Тут вроде не нужен do{ } while(0), один же вызов функции

2019-10-22 01:32 UTC, SWAGLORD1 commented on denisov.pavel/lab1/common.h
> +#define LOG_ERROR_AND_EXIT(...) \
Почему не сделать это inline функцией вместо define? Директивы препроцессора для этой цели уже сильно устарели.

2019-10-22 16:23 UTC, Ppasha9 commented on denisov.pavel/lab1/common.h
> +#define LOG_ERROR_AND_EXIT(...) \
Согласен
Изначально это было сделано для того, чтобы не писать template variadic функции
В итоге решил просто напрямую вызывать syslog

2019-10-22 16:25 UTC, Ppasha9 commented
За совсем про openlog(
Добавил

2019-10-23 00:53 UTC, KotsMikhail approved these changes
Засчитано

2019-10-23 00:53 UTC, merged