First version of first lab
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #12
Opened 2019-10-22 16:32 UTC by MisterProper9000

2019-10-23 00:51 UTC, KotsMikhail requested changes
Системный вызов, который вы используете для отображения сообщения работает не правильно, потому что дочерний терминал закрывается сразу как только заданный скрипт отработает
Также поправьте стиль кодирования, у вас неодинаковые отступы для фигурных скобок и местами неадекватные отступы у операторов

2019-10-23 17:16 UTC, MisterProper9000 commented
Исправил отступы, скобки и пробелы между операторами. Сделал так, что gnome-terminal с выводом сообщения ждёт ввода чтобы закрыться

2019-10-25 01:23 UTC, KotsMikhail requested changes
Отсутствуют сообщения об ошибках при некорректном формате конфига
Некорректная работа демона при изменении конфига: запустил демона, удалил содержимое конфига, демон перестал что-либо делать, хотя команды перечитывать конфиг не поступало.

2019-10-25 10:21 UTC, MisterProper9000 commented
Добавил функцию (в описании коммита ошибся и назвал её методом) для чтения конфига, для хранения одной записи создан класс cfg_entry, добавлены недостающие syslog.

2019-10-26 20:00 UTC, KotsMikhail requested changes
Запустил конфиг с ненаступившей датой - связанное с ней сообщение выводится
Запустил демона со следующим конфигом:
50.10.2019 22:99:00 -m msg
Сообщение выводится каждую минуту, никаких ошибок не выдает

2019-10-27 01:38 UTC, MisterProper9000 commented
Теперь дата и время проверяются на корректность, но случаи, подобные: "31.09.2019 0:0:0" не считаются за ошибку, а записи в структуре tm будет соответствовать дата "1.10.2019 0:0:0"
Также добавил проверку корректности флага.

2019-10-27 17:09 UTC, KotsMikhail requested changes
Теперь программа работает нормально, поправьте стиль кодирования - засчитаю

2019-10-27 17:09 UTC, SWAGLORD1 commented on plaksin.daniil/lab1/daemon.cpp
> +#define ONE_HOUR 3600
Не стоит использовать директивы препроцессора для объявления констант, использует static const переменные

2019-10-27 17:09 UTC, SWAGLORD1 commented on plaksin.daniil/lab1/daemon.cpp
> +bool need_work = true;
Почему эти переменные должны быть глобальными?

2019-10-27 17:09 UTC, SWAGLORD1 commented on plaksin.daniil/lab1/daemon.cpp
> +#define ABS(x) ((x) > 0 ? (x) : -(x))
Чем вас math.abs не устраивает?

2019-10-27 18:18 UTC, MisterProper9000 commented on plaksin.daniil/lab1/daemon.cpp
> +bool need_work = true;
Переменную need_work нельзя сделать локальной, потому что она должна изменяться в функции signal_handler, а она должна быть определённой сигнатуры, чтобы её можно было связать с сигналом и её никак не передать в функцию и не вернуть. Переменную interval можно сделать локальной.

2019-10-27 18:23 UTC, MisterProper9000 commented
Сделал переменную interval локальной, убрал дефайны минуты и часа, потому что они не использовались и заменил ABS на abs из cmath. Переменная need_work оставлена глобальной.

2019-10-28 10:33 UTC, KotsMikhail requested changes

2019-10-28 10:33 UTC, SWAGLORD1 commented on plaksin.daniil/lab1/daemon.cpp
> +bool need_work = true;
Зачем вообще нужна переменная need_work? Если вы думаете, что это спасет вас от работы демона во время перечитывания конфига, то вы ошибаетесь, потому что сигнал генерирует прерывание и код обработки сигнала может начать выполнятся когда вы уже в теле цикла вашего демона. Но вам не стоит волноваться по этому поводу, тело цикла и так не будет возобновляться пока не будет выполнен обработчик сигнала, его можно прервать только другим сигналом

2019-10-28 10:35 UTC, SWAGLORD1 commented
Чуть не забыл: вы ещё не все дефайны заменили на константы.

2019-10-28 22:07 UTC, MisterProper9000 commented
Заменил все дефайны и избавился от need_work

2019-10-29 21:51 UTC, SWAGLORD1 commented
В моем комментарии с подсказкой по поводу синглтона содержался намек на то, как правильно написать эту программу
Кстати, вы уверены, что в стандартных библиотеках нет никаких методов проверки правильности ввода даты и времени?

2019-10-31 21:40 UTC, MisterProper9000 commented
Сделал синглтон.
Я тестировал ввод разных дат и времен и библиотека просто переводит данные числа в нужный формат, например если задать дату и время как "27.10.2016 43244:15:00", то 43244 часов будет переведено в число дней, месяцев и лет и дата соответственно изменится, а остаток от деления на 24 запишется в поле tm_hour

2019-11-02 20:58 UTC, KotsMikhail requested changes
Нет, сделать все поля и методы класса статическими - это не синглтон. Мне говорили, что у вас был курс по паттернам программирования, это правда? И почему приватные поля класса объявлены как protected? Вы же не собираетесь наследоваться от демона.

2019-11-02 22:12 UTC, MisterProper9000 commented
Так как в приоритете было избавление от глобальных переменных, то я считаю, объявление всего статиками достаточным в данной лабораторной + аналогичные решения были у других моих коллег. К тому же возникает проблема, когда я пытаюсь связать обработчик сигнала не со статическим методом класса.

2019-11-02 22:28 UTC, MisterProper9000 commented
Проблему с обработчиками сигнала можно конечно заткнуть френд-функцией

2019-11-03 09:08 UTC, MisterProper9000 commented
Сделал честный синглтон.

2019-11-04 00:44 UTC, KotsMikhail requested changes

2019-11-04 00:44 UTC, SWAGLORD1 commented on plaksin.daniil/lab1/daemon.cpp
> +Daemon* Daemon::get_instance() {
Лучше возвращать ссылку
Отступ фигурных скобок

2019-11-04 00:44 UTC, SWAGLORD1 commented on plaksin.daniil/lab1/daemon.cpp
> +    inst = &instance;
Зачем отдельно хранить ссылку на экземпляр синглтона? Почему не обратится просто к переменной? Она же статическая

2019-11-04 00:44 UTC, SWAGLORD1 commented on plaksin.daniil/lab1/daemon.cpp
> +Daemon* Daemon::inst = 0;
nullptr

2019-11-05 10:32 UTC, KotsMikhail requested changes

2019-11-05 10:32 UTC, SWAGLORD1 commented on plaksin.daniil/lab1/daemon.h
> +    static Daemon* inst;
Неиспользуемая переменная

2019-11-05 10:32 UTC, SWAGLORD1 commented on plaksin.daniil/lab1/daemon.cpp
> +            exit(0);
Рандомная константа

2019-11-05 10:32 UTC, SWAGLORD1 commented on plaksin.daniil/lab1/daemon.cpp
> +            Daemon::get_instance().read_config();
Зачем тут указывать пространство имен класса Demon? Вы и так в нем находитесь

2019-11-06 22:21 UTC, KotsMikhail approved these changes
Засчитано

2019-11-06 22:21 UTC, merged