Lab1 linux daemon
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #13
Opened 2019-10-22 19:32 UTC by sergeevgk

Add lab1 'linux daemon'

2019-10-24 12:00 UTC, KotsMikhail requested changes
В случае некорректных путей программа должна завершатся, а не спамить сообщения об ошибке в лог каждые 30 секунд.
Программа неадекватно работает в случае, когда пути к папкам в конфиге совпадают

2019-10-24 12:00 UTC, KotsMikhail commented on sergeev.georgii/lab1/build.sh
> +g++ -Wall -Werror -o lab1_daemon file_dispatcher.h file_dispatcher.cpp main.cpp
Если вы используете стандарт с11, то собирать следует с опцией -std=c++11, без этого на некоторых версиях компилятора собираться не будет

2019-10-24 12:00 UTC, KotsMikhail commented on sergeev.georgii/lab1/file_dispatcher.cpp
> +    int sent_count = sendfile(destination_file, source_file, nullptr, src_size);
В рамках данной работы я приму такое решение, но имейте в виду, что это не будет работать для файлов размером > 2gb

2019-10-24 12:00 UTC, KotsMikhail commented on sergeev.georgii/lab1/main.cpp
> +FileDispatcher *dispatcher = nullptr;
Почему эти переменные должны быть глобальными?

2019-10-24 12:00 UTC, KotsMikhail commented on sergeev.georgii/lab1/main.cpp
> +void process()
Почему работа с файлами инкапсулированна в отдельный класс - а функции демона - нет?

2019-10-24 12:00 UTC, KotsMikhail commented on sergeev.georgii/lab1/main.cpp
> +        std::string process = "/proc/";
Неиспользуемая переменная

2019-10-24 18:51 UTC, sergeevgk commented on sergeev.georgii/lab1/build.sh
> +g++ -Wall -Werror -o lab1_daemon file_dispatcher.h file_dispatcher.cpp main.cpp
Исправил

2019-10-24 18:51 UTC, sergeevgk commented on sergeev.georgii/lab1/main.cpp
> +FileDispatcher *dispatcher = nullptr;
Исправил, переменные больше не глобальные

2019-10-24 18:51 UTC, sergeevgk commented on sergeev.georgii/lab1/main.cpp
> +void process()
Добавил класс демона

2019-10-24 18:52 UTC, sergeevgk commented on sergeev.georgii/lab1/main.cpp
> +        std::string process = "/proc/";
Неиспользованная переменная убрана

2019-10-25 14:07 UTC, KotsMikhail approved these changes
Засчитано

2019-10-25 14:08 UTC, merged