initial_commit
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #15
Opened 2019-10-24 00:34 UTC by PavelLebed20

2019-10-25 13:37 UTC, KotsMikhail requested changes
Только что созданные файлы помещаются в папку OLD
Скопированные файлы пропадают из папки-источника

2019-10-25 22:41 UTC, PavelLebed20 commented
Чтобы не было путаницы добавил два параметра в конфиг UPDATE_INTERVAL - время, через которое будет происходить обработка, OLD_INTERVAL - время, больше которого файлы считаются "старыми" (все в секундах). Также изменил перемещение файла на копирование (не правильно понял задание сначала).

2019-10-27 01:47 UTC, KotsMikhail requested changes
Демон не выдает сообщений об ошибке в случае некорректного конфига
Следующий конфиг демон считает некорректным:
SRC /home/mikhailkots/Documents/OS_Labs_SPBPU_2019/lebed.pavel/lab1/1
DST /home/mikhailkots/Documents/OS_Labs_SPBPU_2019/lebed.pavel/lab1/2
UPDATE_INTERVAL 30
OLD_INTERVAL 180
Пути в конфиге корректные

2019-10-27 10:46 UTC, PavelLebed20 commented
![изображение](https://user-images.githubusercontent.com/45563221/67633236-7613e200-f8be-11e9-9e0b-824a3d013d0a.png)
 - если не задано одно из значений, ошибка пишется в лог файл, лишние значение не считаются 
ошибкой
![изображение](https://user-images.githubusercontent.com/45563221/67633354-f555e580-f8bf-11e9-82e2-6904e1ffb558.png) - если не получается открыть файл, ошибка пишется в конфиг

2019-10-27 16:54 UTC, KotsMikhail requested changes
Проблема была на моей стороне, сейчас, похоже, все работает нормально. Осталось немного поправить код

2019-10-27 16:54 UTC, SWAGLORD1 commented on lebed.pavel/lab1/main.cpp
> +static FilesMover g_file_mover;
Почему эти переменные должны быть глобальными?

2019-10-27 17:29 UTC, PavelLebed20 commented on lebed.pavel/lab1/main.cpp
> +static FilesMover g_file_mover;
Они используются в нескольких функциях в рамках основного цикла работы программы.
В main - первичная реализация, потом использование либо в цикле, либо в обновлении конфига по команде. Pid и Config используются при внешнем вызове обработки команд.
Можно было бы выделить эту работу в отдельный класс, но так эта сущность единственна в рамках программы, я счел возможным сделать их статическими в рамках main.cpp файла.

2019-10-27 17:37 UTC, PavelLebed20 commented on lebed.pavel/lab1/main.cpp
> +static FilesMover g_file_mover;
file_mover действительно, не обязательно было быть статическим, сделал его параметром в start_proc

2019-10-27 17:49 UTC, PavelLebed20 commented on lebed.pavel/lab1/main.cpp
> +static FilesMover g_file_mover;
А нет, я все-так вас обманул, file_mover - тоже должен быть использован при получении сигнала SIGHUP (установить новые пути из конфига). Добавил туда соответствующий вызов

2019-10-28 08:35 UTC, KotsMikhail requested changes

2019-10-28 08:35 UTC, SWAGLORD1 commented on lebed.pavel/lab1/main.cpp
> +		g_work = false;
Если вы думаете, что это спасет вас от работы демона во время перечитывания конфига, то вы ошибаетесь, потому что сигнал генерирует прерывание и этот код может начать выполнятся когда вы уже в теле цикла вашего демона. Но вам не стоит волноваться по этому поводу, тело цикла и так не будет возобновляться пока не будет выполнен обработчик сигнала, его можно прервать только другим сигналом

2019-10-28 08:35 UTC, SWAGLORD1 commented on lebed.pavel/lab1/main.cpp
> +static FilesMover g_file_mover;
В чём проблема сделать их аргументами функций или инкапсулировать эту функциональность в отдельном классе?

2019-10-28 14:13 UTC, PavelLebed20 commented on lebed.pavel/lab1/main.cpp
> +static FilesMover g_file_mover;
Функция обработки сигнала должна быть глобальной (не в смысле, что слово static обязательно, а в смысле, что передать туда обычный метод класса не статический - не получится), в нашем случае signal_handler, т.к. она будет выполняться внешним вызовом ос. Есть два варианта реализации:
1) Сделать синглтон  класс, который будет эти переменные хранить, и у него статическую функцию 
2) Использую конвертация lambda к std::function  signal(SIGTERM, [](int signum) { /* ... */ });
(возможно не работает до 14-17 версии)
3) Так как сделано сейчас

В 1 и 3 - этот класс\классы будут так или иначе глобальными. 2 позволяет избежать глобальности, но по-моему это излишнее усложнение, по сравнению с очевидно понятным 3 решением.  Т.к. использование этой процедуры - только в одном месте программы,  я считаю вполне возможным сделать эту реализацию непосредственно в main.cpp файле, и использовать глобальные переменные, которые видно только в рамках main.cpp

2019-10-28 14:21 UTC, PavelLebed20 commented on lebed.pavel/lab1/main.cpp
> +		g_work = false;
Тут я скорее хотел обозначить, что в этом месте нужен мбютекс, семафор..., чтобы дать процедуре копирования файла и т.д. отработать, и только после этого запускать обновление конфига. Но на сколько я понял, в рамках этой задаче не обязательно реализовывать подобную структуру

2019-10-28 18:54 UTC, SWAGLORD1 commented on lebed.pavel/lab1/main.cpp
> +static FilesMover g_file_mover;
В данном случае синглтон - общепринятое решение, оно позволяет вам сокрыть реализацию конфига в отдельном классе и предоставить к нему глобальный доступ. Глобальная функция намного лучше глобальной переменной.

2019-10-28 19:02 UTC, SWAGLORD1 commented on lebed.pavel/lab1/main.cpp
> +		g_work = false;
Нет, семафор тут не нужен, обработка сигналов не создает никаких новых потоков и процессов, сигнал просто порождает аппаратное прерывание, которое меняет текущую исполняемую инструкцию. По сути - это просто GOTO. Весь ваш код работает в одном потоке. Единственная проблема, которая в теории может возникнуть - обработчик сигнала может быть прерван другим сигналом, но в данной работе это не должно создать проблем

2019-10-28 20:46 UTC, PavelLebed20 commented
Поменял на синглтон через класс

2019-10-28 20:56 UTC, KotsMikhail approved these changes
Засчитано

2019-10-28 21:00 UTC, merged