Added first lab
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #17
Opened 2019-10-26 00:00 UTC by NikitaSukhanov

2019-10-27 02:13 UTC, KotsMikhail requested changes
Программа принимает конфиг с отрицательным значением временного интервала.
Стиль кодирования стоит поправить, если вы хотите писать все в одном файле - пишите в Си стиле, если хотите писать в С++ стиле - используйте паттерны и не используйте глобальные переменные.

2019-10-27 02:13 UTC, SWAGLORD1 commented on sukhanov.nikita/lab1/daemon_lab1.cpp
> +unsigned time_interval;
Почему эти переменные должны быть глобальными?

2019-10-27 02:13 UTC, SWAGLORD1 commented on sukhanov.nikita/lab1/daemon_lab1.cpp
> +string pid_path = "/var/run/daemon_lab1.pid";
Это вроде бы должно быть константой

2019-10-27 02:13 UTC, SWAGLORD1 commented on sukhanov.nikita/lab1/daemon_lab1.cpp
> +class Utils
Классы лучше располагать в разных файлах, особенно если вы пишете реализацию там же, где объявления

2019-10-27 22:24 UTC, NikitaSukhanov commented
Распихал классы по файлам, переписал класс демона под синглтон Майерса, исправил отрицательное время в конфиге (и баг связанный с тем, что программа падала если запустить её с невалидным именем конфига).

2019-10-28 11:58 UTC, KotsMikhail approved these changes
Засчитано

2019-10-28 19:06 UTC, merged