Add Lab 1
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #18
Opened 2019-10-26 13:01 UTC by pv6

2019-10-27 02:24 UTC, KotsMikhail requested changes
При запуске скрипта установки командой sudo ./build.sh получил ошибку:
touch: cannot touch '': No such file or directory
touch pid file failed: 0
Если у вас есть какие-то параметры сборки, которые должны быть указаны при вызове. то у них либо должны быть дефолтные значения, либо при вызове скрипта без параметров должен выводиться help

2019-10-27 09:16 UTC, pv6 commented
Добавил значение по умолчанию.

2019-10-27 21:13 UTC, KotsMikhail requested changes
Программа завершается без сообщений об ошибке если при обработке sighup получит некорректный конфиг

2019-10-27 21:13 UTC, KotsMikhail commented on vasilyev.peter/lab1/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.10)
На более ранних версиях собираться не будет?

2019-10-27 21:13 UTC, KotsMikhail commented on vasilyev.peter/lab1/daemon.cpp
> +  switch (fork())
switch - странное решение, когда есть всего 2 возможных варианта

2019-10-27 21:13 UTC, KotsMikhail commented on vasilyev.peter/lab1/daemon.cpp
> +  exit(SIGTERM);
Что код сигнала делает в аргументе функции exit?

2019-10-27 21:13 UTC, KotsMikhail commented on vasilyev.peter/lab1/daemon.cpp
> +      kill(old_pid, SIGTERM);
Что будет если послать сигнал несуществующему процессу?

2019-10-27 21:13 UTC, KotsMikhail commented on vasilyev.peter/lab1/config_parser.cpp
> +                          "' wrong number of words!";
Почему не пробросить исключение?

2019-10-27 21:13 UTC, KotsMikhail commented on vasilyev.peter/lab1/daemon.h
> +class Daemon
Лучше использовать синглтон вместо кучи static полей. Тоже самое относится к конфигу

2019-10-27 21:13 UTC, KotsMikhail commented on vasilyev.peter/lab1/config_parser.h
> +public:
Разбивать секции приватности на несколько - плохой стиль

2019-10-27 21:13 UTC, KotsMikhail commented on vasilyev.peter/lab1/main.cpp
> +  switch (fork())
Почему 1-ое ветвление в мейне, а остальная часть демонизации - в отдельной функции?

2019-10-27 21:13 UTC, SWAGLORD1 commented on vasilyev.peter/lab1/daemon.cpp
> +bool Daemon::parseConfig()
Эта функциональность случайно не должна была быть заложена в классе ConfigParser?

2019-10-27 21:13 UTC, SWAGLORD1 commented on vasilyev.peter/lab1/daemon.cpp
> +  log_file.close();
Все эти операции с потоком могут быть неудачными
В случае ошибки они выбрасывают исключения, которые неплохо бы обрабатывать

2019-10-27 23:44 UTC, pv6 commented on vasilyev.peter/lab1/daemon.cpp
> +  switch (fork())
Мне кажется, switch - вполне подходящая конструкция для проверки значения одной переменной, даже если всего два варианта.
Лаконичнее записать вызов один раз в скобках, чем заводить отдельную переменную result = fork(), строить многоуровневые if-ы, и в них каждый раз писать if (result == ...)

2019-10-27 23:45 UTC, pv6 commented on vasilyev.peter/lab1/daemon.cpp
> +  exit(SIGTERM);
Убрал

2019-10-27 23:45 UTC, pv6 commented on vasilyev.peter/lab1/daemon.cpp
> +      kill(old_pid, SIGTERM);
kill вернет код ошибки, но на работоспособность демона это никак не повлияет

2019-10-27 23:45 UTC, pv6 commented on vasilyev.peter/lab1/config_parser.cpp
> +                          "' wrong number of words!";
Исправил на исключение

2019-10-27 23:46 UTC, pv6 commented on vasilyev.peter/lab1/daemon.h
> +class Daemon
Сделал синглтонами

2019-10-27 23:46 UTC, pv6 commented on vasilyev.peter/lab1/config_parser.h
> +public:
Исправил

2019-10-27 23:46 UTC, pv6 commented on vasilyev.peter/lab1/main.cpp
> +  switch (fork())
Перенес первое ветвление в Daemon::start

2019-10-27 23:53 UTC, pv6 commented on vasilyev.peter/lab1/daemon.cpp
> +bool Daemon::parseConfig()
Что бы не сильно все переписывать, разграничил обязаности ConfigParser-a и этого метода:
Теперь ConfigParser получает список имен параметров и считывает их значение в строки. Таким образом, он никак не завязан на Демоне.
Daemon::parseConfig в свою очередь передаёт ConfigParser-у список имен нужных ему параметров и извлекат их значения из строк в нужные ему типы.

2019-10-27 23:53 UTC, pv6 commented on vasilyev.peter/lab1/daemon.cpp
> +  log_file.close();
Добавил обработку исключений

2019-10-27 23:54 UTC, pv6 commented on vasilyev.peter/lab1/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.10)
Если честно, не вникал в совместимости комманд CMake-а. Просто написал версию, чтобы у себя скомпилилось.

2019-10-28 00:09 UTC, pv6 commented
Исправил нелоггированную ошибку при парсинге конфига

2019-10-28 18:16 UTC, KotsMikhail requested changes

2019-10-28 18:16 UTC, SWAGLORD1 commented on vasilyev.peter/lab1/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.10)
Может, тогда лучше вообще убрать эту проверку?

2019-10-28 18:16 UTC, SWAGLORD1 commented on vasilyev.peter/lab1/daemon.cpp
> +  switch (fork())
Почему конструкция if - else не устраивает?

2019-10-28 18:16 UTC, SWAGLORD1 commented on vasilyev.peter/lab1/daemon.cpp
> +  try
Не проще ли написать один try - catch блок в мейне или в теле демона?

2019-10-28 18:16 UTC, SWAGLORD1 commented on vasilyev.peter/lab1/daemon.h
> +class Daemon
Когда пишите синглтон, следует приватить или удалять стандартные конструкторы и операторы копирования

2019-10-28 19:49 UTC, pv6 commented on vasilyev.peter/lab1/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.10)
CMake рекомендует писать минимальную версию для более user-friendly логгирования ошибок, но в принципе можно и убрать. Если на более ранних версиях не собирается, то и так и так не собирётся, а вникать в различия версий CMake-ов сейчас не очень хочется.

2019-10-28 19:54 UTC, pv6 commented on vasilyev.peter/lab1/daemon.cpp
> +  switch (fork())
Потому что конструкция не if - else, а if - else if, где в if-ах проверяется на различные значения одной и той же переменной. Специально для этого и предназначена конструкция switch.
Не нужно заводить отдельную переменную, писать руками сравнения, более наглядный код.

2019-10-28 19:54 UTC, pv6 commented on vasilyev.peter/lab1/daemon.h
> +class Daemon
Верно, забыл в ночи. Исправил

2019-10-28 19:59 UTC, pv6 commented on vasilyev.peter/lab1/daemon.cpp
> +  try
Изменил на более общую обработку исключений в Daemon::start и Daemon::signalHandle. В данном случае количество try - catch сократилось не сильно (3 -> 2), но так, наверное, правильнее, согласен.

2019-10-28 20:38 UTC, KotsMikhail requested changes
Ещё раз: почему нельзя обойтись одним try - catch блоком? Их у вас сейчас 3 и они делают одно и то же. Общее правило - всегда обрабатывать исключения одного типа в одном месте и на самом высоком из возможных уровней, иначе у вас код дублируется.

2019-10-28 20:47 UTC, pv6 commented
Сейчас как раз так и есть: их 2 штуки, в Daemon::start и Daemon::signalHandle. Одним не обойтись, так как signalHandle вызывается системой.

2019-10-28 20:51 UTC, pv6 commented
А, не заметил один в saveLog, сейчас исправлю

2019-10-28 20:52 UTC, KotsMikhail reviewed
Во-первых, их не два. Во-вторых, нет разницы, откуда падает исключение, оно пробрасывается до ближайшего обработчика. Можете сами проверить. Тут без проблем можно обойтись одним

2019-10-28 20:52 UTC, SWAGLORD1 commented on vasilyev.peter/lab1/daemon.cpp
> +  }
Раз

2019-10-28 20:52 UTC, SWAGLORD1 commented on vasilyev.peter/lab1/daemon.cpp
> +      }
Два

2019-10-28 20:52 UTC, SWAGLORD1 commented on vasilyev.peter/lab1/daemon.cpp
> +  }
Три

2019-10-28 20:59 UTC, KotsMikhail approved these changes
Засчитаю, потому что переделать уже не успеете, но обойтись одним блоком можно. Проверьте потом на досуге

2019-10-28 21:00 UTC, merged