Added first lab
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #19
Opened 2019-10-27 12:16 UTC by PawelMelnik

- Added main.cpp file
- Added config file
- Added build script

2019-10-28 19:53 UTC, KotsMikhail requested changes
В случае некорректного пути в конфиге, демон падает с segmentation fault
Демон без ошибок принимает конфиг с отрицательным интервалом

2019-10-28 19:53 UTC, SWAGLORD1 commented on melnik.pavel/lab1/main.cpp
> +#define MAXLEVEL  1
Не стоит использовать директивы препроцессора для задания констант, используйте static const переменные

2019-10-28 19:53 UTC, SWAGLORD1 commented on melnik.pavel/lab1/main.cpp
> +    /* Журналируем любой сбой */
Ну и где журналирование?

2019-10-28 19:53 UTC, SWAGLORD1 commented on melnik.pavel/lab1/main.cpp
> +   else if (signal == SIGTERM) {
Общепринятый стиль отступов в этом случае: } else {
Отступы поехали

2019-10-28 19:53 UTC, SWAGLORD1 commented on melnik.pavel/lab1/build.sh
> +g++ -Wall -Werror -o melnik_daemon main.cpp
Если вы используете 11 стандарт С++ то при сборке следует указывать флаг -std=c++11, без него на некоторых системах и версиях компилятора собираться не будет

2019-10-28 21:01 UTC, PawelMelnik commented on melnik.pavel/lab1/main.cpp
> +#define MAXLEVEL  1
Поправил

2019-10-28 21:01 UTC, PawelMelnik commented on melnik.pavel/lab1/main.cpp
> +    /* Журналируем любой сбой */
Добавил

2019-10-28 21:01 UTC, PawelMelnik commented on melnik.pavel/lab1/main.cpp
> +   else if (signal == SIGTERM) {
Исправил

2019-10-28 21:01 UTC, PawelMelnik commented on melnik.pavel/lab1/build.sh
> +g++ -Wall -Werror -o melnik_daemon main.cpp
Добавил флаг

2019-10-28 21:15 UTC, PawelMelnik commented on melnik.pavel/lab1/main.cpp
> +    /* Журналируем любой сбой */
Ой, не там. Сейчас исправлю

2019-10-28 21:16 UTC, PawelMelnik commented on melnik.pavel/lab1/main.cpp
> +    /* Журналируем любой сбой */
Поправил

2019-10-29 23:10 UTC, KotsMikhail approved these changes
Засчитано

2019-10-29 23:11 UTC, merged