Added linux daemon
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #2
Opened 2019-10-09 20:36 UTC by Chopikov

- Added .cpp, .conf. .sh files
- Changed .gitignore

2019-10-10 12:54 UTC, SWAGLORD1 commented
При попытке собрать ваш код с помощью build.sh я получил несколько ошибок компиляции

2019-10-10 15:03 UTC, KotsMikhail requested changes
В целом неплохо, ваша программа в целом правильно работает, но по коду есть некоторые замечания. Исправите - зачту.

2019-10-10 15:03 UTC, KotsMikhail commented on surikov.ilya/lab1/daemon.cpp
> +        if (!stat(proc, &s) && S_ISDIR(s.st_mode))
Зачем нужна эта проверка? Что пойдет не так, если послать SIGTERM несуществующему процессу?

2019-10-10 15:03 UTC, KotsMikhail commented on surikov.ilya/lab1/daemon.cpp
> +    syslog(LOG_NOTICE, "Successfully working");
Это явно отладочная информация, которой в релизе быть не должно. Демон не должен спамить в лог каждый раз, когда он что-то делает

2019-10-10 15:03 UTC, KotsMikhail commented on surikov.ilya/lab1/daemon.cpp
> +    kill_prev_daemon();
Прежде, чем убивать старого демона, стоит сначала успешно создать нового

2019-10-10 15:03 UTC, KotsMikhail commented on surikov.ilya/lab1/daemon.cpp
> +    sid = setsid();
Тут должно быть ещё одно ветвление, так как в некоторых системах лидер сессии автоматически получает управляющей терминал.

2019-10-10 15:03 UTC, KotsMikhail commented on surikov.ilya/lab1/daemon.cpp
> +        return 0;
Тут должен быть exit, вы сейчас в дочернем процессе, у него нет своего терминала, этот код возврата никто не увидит

2019-10-10 15:03 UTC, KotsMikhail commented on surikov.ilya/lab1/daemon.cpp
> +    set_pid_file();
Это, по идее, должно происходить вместе остановкой предыдущего демона, если он запущен

2019-10-10 15:03 UTC, KotsMikhail commented on surikov.ilya/lab1/daemon.cpp
> +    while (1)
Используйте while(true), это более наглядный стиль кодирования

2019-10-10 15:03 UTC, KotsMikhail commented on surikov.ilya/lab1/daemon.cpp
> +    system( (std::string("mv ") + path_src + std::string(" ") + path_dst).c_str() );
Из всех способов переместить файл вы выбрали самый ненадежный. Вызывать выполнение команды bash из кода С++ следует делать только в крайних случаях, потому что результат сильно зависит от платформы и её настроек. Лучше делать это средствами стандартных библиотек или библиотек Linux, есть много способов добиться нужного результата без bash команды

2019-10-10 15:03 UTC, KotsMikhail commented on surikov.ilya/lab1/build.sh
> +gcc -Wall -Werror daemon.cpp -o daemon_lab -lstdc++
Если вы используете 11 стандарт С++ то при сборке следует указывать флаг -std=c++11, без него на некоторых системах и версиях компилятора собираться не будет

2019-10-10 15:03 UTC, KotsMikhail commented on surikov.ilya/lab1/daemon.cpp
> +    kill_prev_daemon();
Прежде чем убивать старого демона, стоит сначала успешно создать нового

2019-10-10 15:03 UTC, SWAGLORD1 commented on surikov.ilya/lab1/daemon.cpp
> +    sid = setsid();
Тут должно быть ещё одно ветвление, потому что в некоторых системах лидер сессии автоматически получает управляющий терминал

2019-10-10 15:03 UTC, SWAGLORD1 commented on surikov.ilya/lab1/daemon.cpp
> +    set_pid_file();
Это, по идее, должно происходить одновременно с остановкой предыдущего демона, если он запущен

2019-10-10 15:03 UTC, SWAGLORD1 commented on surikov.ilya/lab1/daemon.cpp
> +    while (1)
Лучше использовать while(true), это более наглядный стиль кодирования

2019-10-17 10:46 UTC, KotsMikhail requested changes
Извиняюсь за ревью с опозданием, оповещение от гитхаба потерялось в куче писем
Теперь ваш демон, судя по логам, получает sigterm сразу после старта при запуске с любым конфигом.
Так же я заметил, что программа ничего не выдает при запуске без параметров, это тоже стоит исправить

2019-10-21 01:51 UTC, KotsMikhail approved these changes
Засчитано

2019-10-21 01:51 UTC, merged