Add lab 1
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #20
Opened 2019-10-27 21:04 UTC by Mitrofanova-Alina

2019-10-28 19:37 UTC, KotsMikhail requested changes
При попытке собрать вашу программу командой sudo ./build.sh получил следующую ошибку:
main.cpp: In function ‘void SetPidFile()’:
main.cpp:87:17: error: cannot resolve overloaded function ‘is_open’ based on conversion to type ‘bool’
if (ofs.is_open) {
В задании указано, что интервал должен быть в конфиге, у вас его нет

2019-10-28 19:37 UTC, SWAGLORD1 commented on mitrofanova.alina/lab1/main.cpp
> +	else {
Общепринятый стиль выглядит так: } else {

2019-10-28 19:37 UTC, SWAGLORD1 commented on mitrofanova.alina/lab1/main.cpp
> +		syslog(LOG_INFO, "Don't open file");
"Don't open file" переводится как "Не открывать файл". Сомневаюсь, что это то, что имелось в виду

2019-10-28 19:37 UTC, SWAGLORD1 commented on mitrofanova.alina/lab1/build.sh
> +gcc -Wall -Werror main.cpp -o Lab1_Daemon -lstdc++
Если вы используете 11 стандарт С++ то при сборке следует указывать флаг -std=c++11, без него на некоторых системах и версиях компилятора собираться не будет

2019-10-29 08:02 UTC, Mitrofanova-Alina commented
Исправила замечания. Жду ответа

2019-10-29 23:36 UTC, KotsMikhail requested changes
При посыле сигнала sighup программа всегда завершается с ошибкой о несуществующем конфиге
Программу можно запустить, не указывая в конфиге интервал, при этом демон будет работать с интервалом 0 и не выдаст никаких ошибок.

2019-10-29 23:36 UTC, SWAGLORD1 commented on mitrofanova.alina/lab1/main.cpp
> +			syslog(LOG_ERR, "Error pid and could not kill daemon");
Это сообщение об ошибке переводится как "Ошибка pid и не смог убить демона"

2019-10-29 23:36 UTC, SWAGLORD1 commented on mitrofanova.alina/lab1/main.cpp
> +	char* buffer = (char*)malloc(80);
Использовать рандомные константы в коде - плохой стиль, лучше объявлять их в начале программы

2019-10-29 23:36 UTC, SWAGLORD1 commented on mitrofanova.alina/lab1/main.cpp
> +std::string pid_file = "/var/run/lab1_daemon.pid";
Путь к пид файлу должен быть константой

2019-11-13 18:56 UTC, Mitrofanova-Alina commented
Исправила замечания.

2019-11-14 19:39 UTC, KotsMikhail approved these changes
Засчитано

2019-11-14 19:39 UTC, merged