[Lab1] Vitaliy Plastinin
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #21
Opened 2019-10-28 17:25 UTC by vitalik239

Task 13

2019-10-30 21:49 UTC, KotsMikhail requested changes
Программа завершается без ошибок и ничего не делает, если запустить её с некорректным ключевым словом
Если указать в конфиге два одинаковых пути, демон не выдаст никаких ошибок и просто удалит все файлы логов
Спамить в лог на каждое действие демона не нужно, достаточно только события запуска\завершения\сигнала + ошибки. Все остальное - отладочная информация, которой не должно быть в релизе.
Стиль отступа фигурных скобок в коде непостоянный

2019-10-30 21:49 UTC, SWAGLORD1 commented on plastinin.vitaliy/lab1/daemon.cpp
> +#define PID_PATH "/var/run/daemon.pid"
Не используйте директивы препроцессора для объявления констант, используйте static const переменые

2019-10-30 21:49 UTC, SWAGLORD1 commented on plastinin.vitaliy/lab1/daemon.cpp
> +char config_path[MAX_PATH] = "conf.txt";
Имя конфига лучше сделать аргументом запуска программы

2019-10-30 21:49 UTC, SWAGLORD1 commented on plastinin.vitaliy/lab1/daemon.cpp
> +	if (conf == NULL) {
Лучше использовать nullptr вместо NULL

2019-10-30 21:49 UTC, SWAGLORD1 commented on plastinin.vitaliy/lab1/daemon.cpp
> +		exit(1);
Используйте стандартный enum для значений выхода вместо магических констант

2019-10-30 21:49 UTC, SWAGLORD1 commented on plastinin.vitaliy/lab1/daemon.cpp
> +			kill(pid, SIGTERM);
Что будет, если послать сигнал несуществующему процессу?

2019-10-30 21:49 UTC, SWAGLORD1 commented on plastinin.vitaliy/lab1/daemon.cpp
> +		kill_daemon();
Перед тем, как убивать предыдущий экземпляр демона, стоит сначала успешно создать новый

2019-10-30 21:49 UTC, SWAGLORD1 commented on plastinin.vitaliy/lab1/daemon.cpp
> +		while(1) {
Лучше использовать while(true)

2019-11-01 16:40 UTC, vitalik239 commented
Рассмотрел крайние случаи, рефактор, enum ошибок

2019-11-02 21:17 UTC, KotsMikhail requested changes
Стиль отступов фигурных скобок все ещё не одинаковый

2019-11-02 21:17 UTC, SWAGLORD1 commented on plastinin.vitaliy/lab1/daemon.cpp
> +enum {
Под стандартным enum я имел в виду EXIT_SUCCESS и EXIT_FAILURE из стандартной библиотеки

2019-11-02 21:17 UTC, SWAGLORD1 commented on plastinin.vitaliy/lab1/build.sh
> +g++ daemon.cpp -Wall -Werror -o daemon
Если вы используете что-то из с++11, то собирать следует с флагом -std=c++11, иначе на некоторых версиях компилятора не соберется

2019-11-02 21:18 UTC, SWAGLORD1 commented
Ещё я не увидел ответ на свой вопрос по поводу посылки сигнала несуществующему процессу

2019-11-03 10:13 UTC, vitalik239 commented on plastinin.vitaliy/lab1/build.sh
> +g++ daemon.cpp -Wall -Werror -o daemon
nullptr использую после прошлого ревью

2019-11-03 10:59 UTC, vitalik239 commented on plastinin.vitaliy/lab1/daemon.cpp
> +			kill(pid, SIGTERM);
Если pid = 0, то убьём всех в своей группе процессов.
Иначе, если процесса нет, то ничего не произойдёт.

2019-11-03 11:01 UTC, vitalik239 commented
Поправил, добавил ответ на вопрос

2019-11-04 00:50 UTC, KotsMikhail approved these changes
Засчитано

2019-11-04 00:50 UTC, merged