Lab1 Lavrichenko Olga
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #22
Opened 2019-10-28 20:54 UTC by OLavrik

2019-10-29 20:05 UTC, KotsMikhail requested changes
Запускаю скрипт сборки командой sudo bash build.sh
Получаю следующий вывод:
build.sh: line 2: $'\r': command not found
build.sh: line 4: $'\r': command not found
build.sh: line 5: syntax error in conditional expression
'uild.sh: line 5: syntax error near `]]
'uild.sh: line 5: `if [[ ! -f "$pid_log" ]]

2019-11-19 13:36 UTC, OLavrik commented
На самом деле код тот же, но почему-то при переносе из убунты ругается на пробелы и переносы. Проверила на маке работает, но самая первая версия работала убунту

2019-11-19 13:37 UTC, OLavrik commented
Получается, что не нужно запариваться с установкой убунты, а просто на маке делать

2019-11-20 22:14 UTC, KotsMikhail requested changes
Ошибка при установке никак не поменялась

2020-02-03 17:10 UTC, KotsMikhail requested changes
Если запустить демона с предложенным конфигом, то демон всегда выходит на старте с сообщением о том, что он не может открыть pid файл

2020-02-13 13:44 UTC, OLavrik commented
запуск:
sudo bash build.sh 
./daemon_lab_14 config.conf

2020-02-15 22:36 UTC, KotsMikhail requested changes
Напоминания срабатывают для временных меток, которые ещё не наступили
Напоминания не повторяются для временных меток, которые уже наступили

2020-03-02 01:45 UTC, KotsMikhail requested changes
Работает вроде правильно
Разные классы должны быть в разных файлах, объявление и реализация - тоже
Разный стиль отступов фигурных скобок
Разный стиль наименования полей классов

2020-03-02 01:45 UTC, SWAGLORD1 commented on lavrichenko.olga/lab1/daemon_source.cpp
> +#define SLEEP_TIME 1
Лучше использовать static const
И зачем вам 2 переменные EPS и SLEEP_TIME, которые, кажется, имеют один и тот же смысл?

2020-03-02 01:45 UTC, SWAGLORD1 commented on lavrichenko.olga/lab1/daemon_source.cpp
> +typedef enum {w = 30, d = 86400, h = 3600, NONE = 0} EventType; // 604800
лучше использовать enum class

2020-03-02 01:45 UTC, SWAGLORD1 commented on lavrichenko.olga/lab1/daemon_source.cpp
> +} config_reader;
Почему эта переменная должна быть глобальной?

2020-03-02 01:45 UTC, SWAGLORD1 commented on lavrichenko.olga/lab1/daemon_source.cpp
> +} reminder;
Почему эта переменная должна быть глобальной?
И не стоит так объявлять глобальные переменные, плохая читаемость кода

2020-03-02 01:45 UTC, SWAGLORD1 commented on lavrichenko.olga/lab1/daemon_source.cpp
> +struct ConfigReader {
Не стоит использовать структуры в С++ коде

2020-03-02 01:45 UTC, SWAGLORD1 commented on lavrichenko.olga/lab1/daemon_source.cpp
> +		_form += _print_text_path + " ";
Я засчитаю такое решение, но почему бы просто не написать в терминале то, что нужно командой echo?

2020-04-19 04:03 UTC, merged