Surikov.ilya
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #24
Opened 2019-11-23 00:03 UTC by Chopikov

I guess commits from first lab are here because of "Squash and merge" but I'm not sure. In base repository there are only one commit in this branch. I don't know how to fix it.

2019-11-23 20:10 UTC, SWAGLORD1 commented
Не могли бы вы обойтись без включения bits/types/siginfo_t.h? Я извиняюсь, но на моем компе этот заголовочный файл отказывается подключатся, несмотря на то, что библиотека с ним вроде как установлена. Решения из интернета так же не помогли.

2019-11-23 20:51 UTC, Chopikov commented
@SWAGLORD1 Убрал данную библиотеку, прошу прощения, ее автоматически предложило подключить

2019-11-24 14:03 UTC, KotsMikhail requested changes
В случае запуска программы с взаимодействием через именованный канал клиент упал по таймауту после первого сообщения.
В остальном у вас все те же ошибки, что и у Козлова, загляните в его пул реквест и исправьте.
Кстати, как так получилось, что ваши работы совпадают примерно процентов на 50?

2019-11-24 19:35 UTC, Chopikov commented
Исправил все замечания
Теперь все работает как нужно

2019-11-25 17:31 UTC, KotsMikhail requested changes
Пользователь должен вводить ходы волка с клавиатуры

2019-11-25 21:07 UTC, Chopikov commented
@SWAGLORD1 Могу я тоже доделать за завтрашний день, пожалуйста?

2019-11-26 10:41 UTC, Chopikov commented
Исправил
Надеюсь на понимание и прощение за просроченный на день дедлайн(

2019-11-27 23:28 UTC, KotsMikhail requested changes
Неплохо было бы добавить обработку sigint чтобы ваши приложения можно было нормально было завершать с клавиатуры

2019-11-27 23:28 UTC, SWAGLORD1 commented on surikov.ilya/lab2/client/goat.h
> +    Goat(const Goat&);
Конструктор объявлен в заголовке, но не реализован и нигде не используется

2019-11-27 23:28 UTC, SWAGLORD1 commented on surikov.ilya/lab2/client/goat.h
> +    Goat(const Goat&);
Конструктор и оператор копирования в синглтоне следует удалять

2019-11-27 23:28 UTC, SWAGLORD1 commented on surikov.ilya/lab2/conn/conn_fifo.cpp
> +        memcpy(buf, (void*)&fifo_buf, count);
Зачем вам двойная буферизация при чтении?

2019-11-27 23:28 UTC, SWAGLORD1 commented on surikov.ilya/lab2/host/client_info.h
> +    explicit ClientInfo(int pid) : pid(pid), attached(pid != 0), count_dead(0)
Что делает ключевое слово explicit и зачем оно тут?

2019-12-02 09:58 UTC, Chopikov commented on surikov.ilya/lab2/host/client_info.h
> +    explicit ClientInfo(int pid) : pid(pid), attached(pid != 0), count_dead(0)
Предотвращает неявное преобразование типов при инициализации. То есть чтобы нельзя было написать ClientInfo c_i = 1.

2019-12-02 10:02 UTC, Chopikov commented on surikov.ilya/lab2/conn/conn_fifo.cpp
> +        memcpy(buf, (void*)&fifo_buf, count);
Убрал

2019-12-02 10:02 UTC, Chopikov commented on surikov.ilya/lab2/client/goat.h
> +    Goat(const Goat&);
Удалил

2019-12-02 10:03 UTC, Chopikov commented on surikov.ilya/lab2/client/goat.h
> +    Goat(const Goat&);
Исправил

2019-12-02 10:21 UTC, Chopikov commented
Прошу прощения, что так долго исправлял
Был очень занят подготовкой научной статьи

2019-12-03 23:32 UTC, KotsMikhail requested changes

2019-12-03 23:32 UTC, SWAGLORD1 commented on surikov.ilya/lab2/conn/conn_fifo.cpp
> +        memcpy(buf, &fifo_buf, count);
Буферизация все ещё на месте. В чём проблема сразу читать в нужную область памяти?

2019-12-05 20:51 UTC, Chopikov commented on surikov.ilya/lab2/conn/conn_fifo.cpp
> +        memcpy(buf, &fifo_buf, count);
Убрал

2019-12-06 00:14 UTC, SWAGLORD1 commented
Убрать буферизацию нужно везде, а не только в одном соединении

2019-12-08 08:40 UTC, Chopikov commented
Исправил

2019-12-09 10:36 UTC, KotsMikhail approved these changes
Засчитано

2019-12-09 10:40 UTC, merged