Fedorov.dmitrii
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #26
Opened 2019-11-23 13:32 UTC by dimaaa1fed

Add lab 2

2019-11-23 21:00 UTC, KotsMikhail requested changes
При сборке получил следующее сообщение об ошибке:

connections/conn_fifo.cpp: In constructor ‘Conn::Conn(int, bool)’:
connections/conn_fifo.cpp:23:27: error: ‘unlink’ was not declared in this scope
    unlink(filename.c_str());
                           ^
connections/conn_fifo.cpp: In member function ‘bool Conn::Read(void*, size_t)’:
connections/conn_fifo.cpp:55:38: error: ‘read’ was not declared in this scope
       if (read(fifo_desc, &msg, count) == -1) {
                                      ^
connections/conn_fifo.cpp:57:25: error: ‘close’ was not declared in this scope
          close(fifo_desc);
                         ^
connections/conn_fifo.cpp:60:25: error: ‘close’ was not declared in this scope
          close(fifo_desc);
                         ^
connections/conn_fifo.cpp: In member function ‘bool Conn::Write(void*, size_t)’:
connections/conn_fifo.cpp:75:38: error: ‘write’ was not declared in this scope
       if (write(fifo_desc, buf, count) == -1) {
                                      ^
connections/conn_fifo.cpp:77:25: error: ‘close’ was not declared in this scope
          close(fifo_desc);
                         ^
connections/conn_fifo.cpp:79:25: error: ‘close’ was not declared in this scope
          close(fifo_desc);
                         ^

2019-11-23 21:45 UTC, dimaaa1fed commented
Добавил unistd.h, должно теперь собраться
Хотя у меня почему-то собиралось без нее

2019-11-25 00:27 UTC, KotsMikhail requested changes
При запуске с именованным каналом при подключении клиента получил следующую ошибку на стороне хоста:
Launch host with pid: 4620
Connection: fifo created with name - /tmp/4620
Wolf constructed
Client connected: pid is 4642
START GAME AS WOLF
Goat: I am alive with full hp
open() : No such file or directory
*** Error in `./host_fifo': free(): invalid next size (normal): 0x0000000000867360 ***

При запуске с сокетом клиент завершил свою работу сразу после подключения без каких-либо сообщений об ошибке

Ходы волка на стороне хоста должен вводить пользователь с клавиатуры

2019-11-25 00:27 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab2/client/client.cpp
> +#include <stdlib.h>
Тут тоже нужен <unistd.h>

2019-11-25 00:27 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab2/host/wolf.cpp
> +#include <signal.h>
Тут тоже нужен <unistd.h>

2019-11-25 19:40 UTC, dimaaa1fed commented
Поправил

2019-11-26 23:19 UTC, SWAGLORD1 commented
Вы уверены, что вы коммитнули все, что нужно? Я сейчас вижу все те же самые проблемы, о которых я вам уже писал

2019-11-27 15:03 UTC, dimaaa1fed commented
Все изменения на месте
Для большей уверенности склонировал на linuxMint cinnamon последние изменения: makefile собирает, sock, fifo, инпут - все работает

2019-11-28 23:50 UTC, KotsMikhail requested changes
Ходы хоста и клиента должны происходить в обратном порядке: сначала клиент выдает случайное число, затем пользователь вводит с хоста ответ
Желательно добавить обработку siging чтобы программы можно было корректно завершить с клавиатуры
Клиент с сокетом завершается без сообщений об ошибке сразу после подключения

2019-11-28 23:50 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab2/client/goat.cpp
> +      std::uniform_int_distribution<int> dis(1, 100);
Параметры игры лучше делать константами

2019-11-28 23:50 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab2/client/goat.h
> +   sem_t* sem_host;
Семафоры нигде не закрываются

2019-11-28 23:50 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab2/client/goat.h
> +   sem_t* sem_client;
Семафоры нигде не закрываются

2019-11-28 23:50 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab2/client/goat.cpp
> +void Goat::Terminate () {
Эта функция должна быть деструктором, тогда её не надо будет вызывать после каждой ошибки

2019-11-28 23:50 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab2/client/goat.cpp
> +  if (Conn::GetType() == "conn_fifo") {
Почему для именованного пайпа не нужны семафоры?

2019-11-28 23:50 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab2/connections/conn_fifo.cpp
> +   if ((desc = open(filename.c_str(), O_RDONLY)) == -1) {
Удобнее дескрипторы на чтение/запись создавать при установке соединения

2019-12-01 17:39 UTC, dimaaa1fed commented on fedorov.dmitrii/lab2/connections/conn_fifo.cpp
> +   if ((desc = open(filename.c_str(), O_RDONLY)) == -1) {
Сделал, после этого изменения семафоры используются как и в других реализациях conn (В прошлой реализации вызов write на хосте и read на клиенте должны были вызываться одновременно, для передачи сообщения между процессами, иначе процесс останавливался и ждал соответствующего вызыва)

2019-12-01 17:40 UTC, dimaaa1fed commented on fedorov.dmitrii/lab2/client/goat.cpp
> +void Goat::Terminate () {
Сделал инструктором, возвращаю инстанс по указателю, для корректного завершения при обработке сигналов
Так же в интерфейс conn добавился метод HasError, что бы после открытия (создается соединение в конструкторе) узнать есть ли ошибки

2019-12-01 17:41 UTC, dimaaa1fed commented on fedorov.dmitrii/lab2/client/goat.h
> +   sem_t* sem_client;
close на клиенте, unlink на хосте добавил

2019-12-01 17:41 UTC, dimaaa1fed commented on fedorov.dmitrii/lab2/client/goat.cpp
> +      std::uniform_int_distribution<int> dis(1, 100);
Вынес в файл support/game_consts.h

2019-12-01 17:44 UTC, dimaaa1fed commented on fedorov.dmitrii/lab2/client/goat.cpp
> +  if (Conn::GetType() == "conn_fifo") {
Порядок игры изменил, обработку SIGINT добавил
Сокеты не удалось воспроизвести: на Ubutntu и LinuxMint у меня все работает

2019-12-01 17:44 UTC, dimaaa1fed commented
Порядок игры изменил, обработку SIGINT добавил
Сокеты не удалось воспроизвести: на Ubutntu и LinuxMint у меня все работает

2019-12-03 00:49 UTC, KotsMikhail requested changes
Для того, чтобы узнать о наличии ошибок, следует использовать механизм обработки исключений
Не могу сходу понять, что не так с вашим сокетом, я постараюсь разобраться, а пока вот остальные проблемы, которые я нашел

2019-12-03 00:49 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab2/connections/conn.h
> +   int* internal_data;
Не очень хорошее решение, так как теряется семантика дополнительных полей и ваш код становится очень тяжело читать. Предлагаю хранить указатель на область памяти, в реализациях объявлять структуру и кастовать эту область памяти к ней.

2019-12-07 11:01 UTC, dimaaa1fed commented on fedorov.dmitrii/lab2/connections/conn.h
> +   int* internal_data;
Убрал HasError, добавил механиз обработки исключений
Исправил непонятную семантику полей

2019-12-07 21:32 UTC, KotsMikhail requested changes
Теперь клиент со связью через сокет после открытия падает с сообщением "sem_host wasn't opened"
Так же заметил, что хост ведет себя неадекватно при попытке подключить во время игры 2-ого клиента
И поправьте фигурные скобки, они у вас опять везде в разном стиле

2019-12-08 09:51 UTC, dimaaa1fed commented
Поправил

2019-12-09 21:19 UTC, KotsMikhail requested changes
Сейчас все нормально работает, добавьте стандартный модуль в одном месте, чтобы все собиралось на всех системах. С фигурными скобками все ещё не все в порядке, в кейсах оператора switch они не нужны, и форматирование в некоторых местах все ещё разное

2019-12-09 21:19 UTC, KotsMikhail commented on fedorov.dmitrii/lab2/client/goat.cpp
> +#include <stdexcept>
#include <unistd.h>

2019-12-09 21:19 UTC, KotsMikhail commented on fedorov.dmitrii/lab2/connections/conn_fifo.cpp
> +   *((Msg*)buf) = msg;
Зачем тут буферизация? Почему нельзя сразу читать в buf?

2019-12-10 17:37 UTC, dimaaa1fed commented
Исправил замечания

2019-12-11 22:23 UTC, KotsMikhail approved these changes
Засчитано

2019-12-11 22:23 UTC, merged