DenisovPavel #Lab2
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #27
Opened 2019-11-23 13:35 UTC by Ppasha9

2019-11-23 21:04 UTC, SWAGLORD1 commented
Не могли бы вы обойтись без включения bits/types/siginfo_t.h? Я извиняюсь, но на моем компе этот заголовочный файл отказывается подключатся, несмотря на то, что библиотека с ним вроде как установлена. Решения из интернета так же не помогли.

2019-11-23 21:18 UTC, Ppasha9 commented
Поменял bits/types/siginfo_t.h на csignal.
Теперь вроде должно работать.

2019-11-24 09:35 UTC, Ppasha9 commented
Добавил заголовочный файл errno.h, так как я везде использую errno
Странно, что у меня спокойно собиралось и работало без него, как и у студентка Козлова
Надеюсь теперь соберется

2019-11-24 16:42 UTC, Ppasha9 commented
Внес некоторые правки
Убрал ненужный параметр в makefile и подправил сообщения в клиенте и хосте

2019-11-25 01:08 UTC, KotsMikhail requested changes
После запуска и завершения хоста с именованным каналом, при повторном его запуске к нему невозможно подключить клиента, хост падает с сообщением об ошибке соединения

2019-11-25 01:08 UTC, KotsMikhail commented on denisov.pavel/lab2/client/client.h
> +    const int DEAD_MAX_RAND  = 50;
Возможно, эти переменные должны быть статическими

2019-11-25 01:08 UTC, KotsMikhail commented on denisov.pavel/lab2/connections/src/conn_fifo.cpp
> +int fifoID;
От глобальных переменных следует избавиться

2019-11-25 01:08 UTC, SWAGLORD1 commented on denisov.pavel/lab2/client/client_implement.cpp
> +        sem_wait(semaphore_client);
Ожидание семафора без таймаута

2019-11-25 01:08 UTC, SWAGLORD1 commented on denisov.pavel/lab2/host/host.h
> +    int  GetNewRandomNumber       ();
Дублирование кода клиента. Возможно, эту функцию лучше вынести отдельно?

2019-11-25 09:08 UTC, Ppasha9 commented on denisov.pavel/lab2/client/client_implement.cpp
> +        sem_wait(semaphore_client);
Если у нас теперь хост ждет ввода числа с клавиатуры, то получается, что здесь должно быть ожидание семафора без таймаута. Иначе, если пользователь на хосте будет долго думать над новым числом, игра завершится. Разве так должно быть?

2019-11-25 10:17 UTC, Ppasha9 commented on denisov.pavel/lab2/client/client.h
> +    const int DEAD_MAX_RAND  = 50;
Поправил

2019-11-25 10:17 UTC, Ppasha9 commented on denisov.pavel/lab2/connections/src/conn_fifo.cpp
> +int fifoID;
Поправил

2019-11-25 10:18 UTC, Ppasha9 commented on denisov.pavel/lab2/host/host.h
> +    int  GetNewRandomNumber       ();
Убрал это у хоста, так как теперь числа вводятся с клавиатуры.
У клиента оставил, сделал статик функцией

2019-11-25 10:21 UTC, Ppasha9 reviewed
Поправил все замечания.
Насчет таймаута у клиента: так и не понял зачем он нужен, ведь пользователь на хосте теперь вводит числа с клавиатуры.
Насчет проблемы с повторным запуском хоста с именованным каналом. Возможно, хост был завершен через комбинацию клавиш Ctrl + C, так что добавил обработку сигнала SIGINT в хост. Теперь должно работать, по крайней мере у меня работает корректно.

2019-11-25 20:25 UTC, KotsMikhail requested changes
Очередность ходов должна быть обратной. Сначала козлята делают свой ход, затем волк их ловит.
Вариант программы с сокетом никак не реагирует на ввод данных с клавиатуры после установки соединения.
Программа позволяет вводить любые числа и неадекватно реагирует на ввод строки

2019-11-25 20:25 UTC, SWAGLORD1 commented on denisov.pavel/lab2/client/client.h
> +    explicit Client (pid_t pid);
Что делает ключевое слово explicit и зачем оно тут?

2019-11-25 20:25 UTC, SWAGLORD1 commented on denisov.pavel/lab2/client/client_implement.cpp
> +        sem_wait(semaphore_client);
Вы правы, тут действительно не должно быть таймаута, моя ошибка

2019-11-25 20:25 UTC, SWAGLORD1 commented on denisov.pavel/lab2/connections/conn_interfaces/conn.h
> +    int *additionalArgs;
Не очень хорошее решение, так как теряется семантика дополнительных полей и ваш код становится очень тяжело читать.  Предлагаю хранить указатель на область памяти, в реализациях объявлять структуру и кастовать эту область памяти к ней.

2019-11-25 20:25 UTC, SWAGLORD1 commented on denisov.pavel/lab2/connections/conn_interfaces/conn.h
> +    bool isHost, wasCreated;
Переменная wasCreated не используется в conn_mq. Может, это тоже дополнительный аргумент?

2019-11-26 00:20 UTC, Ppasha9 commented on denisov.pavel/lab2/connections/conn_interfaces/conn.h
> +    bool isHost, wasCreated;
Согласен, не заметил. Вынес переменную wasCreated в дополнительные аргументы.

2019-11-26 00:21 UTC, Ppasha9 commented on denisov.pavel/lab2/connections/conn_interfaces/conn.h
> +    int *additionalArgs;
Переделал на void *pmem, то есть на указатель на область памяти, который в реализациях просто кастую к нужной структуре. Надеюсь теперь код более читаемый)

2019-11-26 00:23 UTC, Ppasha9 commented on denisov.pavel/lab2/client/client.h
> +    explicit Client (pid_t pid);
Убрал explicit.
По сути, он не нужен. Просто я это добавил, чтобы нельзя было написать Client cl = pid, хотя у нас клиент является синглтоном, и такой ситуации просто не может быть.

2019-11-26 00:24 UTC, Ppasha9 commented
Поменял очередность ходов. Теперь сначала ходит козленок, потом волк. Ошибку с реализацией сокетов поправил. Вроде должно работать. 
Так же добавил проверку ввода пользователя на стороне хоста. Теперь при невалидном вводе хост пишет что именно неправильно и просит попробовать еще раз.

2019-11-26 23:59 UTC, KotsMikhail requested changes
Не собирается, сообщение об ошибке следующее:

./client/client_implement.cpp: In member function ‘bool Client::OpenConnection()’:
./client/client_implement.cpp:48:5: error: expected ‘;’ before ‘std’
     std::cout << "Semaphores created. Client's pid: " << getpid() << std::endl;
     ^
./client/client_implement.cpp:48:79: error: statement has no effect [-Werror=unused-value]
     std::cout << "Semaphores created. Client's pid: " << getpid() << std::endl;

2019-11-27 03:29 UTC, Ppasha9 commented
Тупая ошибка.
Поправил.

2019-11-28 23:31 UTC, SWAGLORD1 commented
Вариант программы с сокетом зависает после установки соединения с клиентом и не реагирует на ввод с клавиатуры

2019-11-29 09:06 UTC, Ppasha9 commented
Проверил на Linux Mint 19 Cinnamon, и действительно хост зависает при подключении клиента. Странно что на Ubuntu 18.04 все работало прекрасно.
В любом случае, поправил ошибку.

2019-12-01 23:45 UTC, SWAGLORD1 commented
Засчитано

2019-12-01 23:45 UTC, merged