Added lab2
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #28
Opened 2019-11-23 22:27 UTC by MaximSmolskiy

2019-11-25 08:01 UTC, KotsMikhail requested changes
Ходы волка должен вводить пользователь с клавиатуры и результат должен выводиться в консоль

2019-11-25 09:23 UTC, MaximSmolskiy commented
Исправил

2019-11-25 19:52 UTC, KotsMikhail requested changes
Очередность ходов должна быть обратной. Сначала козлята делают свой ход, затем волк их ловит.
Хост позволяет вводить любые целые числа, при вводе текстовой строки поведение неадекватное.
Поведения хоста и клиента должны быть инкапсулированы в отдельные классы.

2019-11-25 22:46 UTC, MaximSmolskiy commented
Исправил

2019-11-27 19:48 UTC, KotsMikhail approved these changes
Засчитано

2019-11-27 21:11 UTC, merged