Tunikov.dmitrii lab2
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #29
Opened 2019-11-24 19:33 UTC by DmitriiTunikov

2019-11-25 18:34 UTC, KotsMikhail requested changes
В целом неплохо, работает вроде правильно. Стоит добавить обработку сигнала SIGINT чтобы хоста и клиента можно было прервать с клавиатуры

2019-11-25 18:34 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab2/conn/conn_fifo.cpp
> +const char* Conn::channel_name;
Подумайте, как избавится от глобальны переменных

2019-11-25 18:34 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab2/client/client.cpp
> +int main(int argc, char* argv[])
Реализовывать main и функции класса в одном модуле - немного странное решение. Почему бы их не разнести в разные файлы?

2019-11-25 18:34 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab2/makefile
> +	echo host_$(1) was builded;
3-я форма глагола build - built. А ещё в данном случае правильнее использовать present perfect

2019-11-25 18:34 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab2/conn/conn_fifo.cpp
> +    if ((desc = open(channel_name, O_RDONLY)) == -1)
Эффективнее создавать дескриптор для чтения\записи в конструкторе и закрывать его при закрытии соединения

2019-11-25 18:34 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab2/client/client.h
> +    explicit Client(int host_pid);
Конструктор и оператор копирования стоит заприватить или удалить

2019-11-25 18:34 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab2/interfaces/conn.h
> +    static int listener;
Хранить все переменные для всех типов взаимодействия в интерфейсе - не лучшее решение

2019-11-25 20:56 UTC, DmitriiTunikov commented
Исправил замечания

2019-11-25 21:34 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab2/interfaces/conn.h
> +    static int listener;
Исправил

2019-11-25 21:34 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab2/client/client.h
> +    explicit Client(int host_pid);
Исправил

2019-11-25 21:35 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab2/conn/conn_fifo.cpp
> +    if ((desc = open(channel_name, O_RDONLY)) == -1)
Исправил

2019-11-25 21:35 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab2/makefile
> +	echo host_$(1) was builded;
Исправил

2019-11-25 21:35 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab2/client/client.cpp
> +int main(int argc, char* argv[])
Исправил

2019-11-25 21:35 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab2/conn/conn_fifo.cpp
> +const char* Conn::channel_name;
Исправил

2019-11-26 23:26 UTC, KotsMikhail approved these changes
Засчитано

2019-11-26 23:27 UTC, merged