Wrote a disk monitor daemon
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #3
Opened 2019-10-09 22:10 UTC by MikhailNakhatovich

- Changed `.gitignore`
- Added example of the configuration file
- Added source code
- Added `build.sh`

2019-10-12 02:09 UTC, KotsMikhail requested changes
В целом неплохо, ваша программа в целом правильно работает, но по коду есть некоторые замечания. Исправите - зачту.

2019-10-12 02:09 UTC, KotsMikhail commented on nakhatovich.mikhail/lab1/build.sh
> +g++ -Wall -Werror types.h utils.h utils.cpp inotify.h inotify.cpp config.h config.cpp daemon.cpp -o daemon
Если вы используете 11 стандарт С++ то при сборке следует указывать флаг -std=c++11, без него на некоторых системах и версиях компилятора собираться не будет

2019-10-12 02:09 UTC, KotsMikhail commented on nakhatovich.mikhail/lab1/config.h
> +    config_t() = delete;
Когда пишите синглтон, конструктор копирования и оператор копирования так же стоит удалять.

2019-10-12 02:09 UTC, KotsMikhail commented on nakhatovich.mikhail/lab1/daemon.cpp
> +inotify_t inotify;
Почему эти переменные обязательно должны быть глобальными?

2019-10-12 02:09 UTC, KotsMikhail commented on nakhatovich.mikhail/lab1/daemon.cpp
> +    if (setsid() < 0)
После создания сессии должно быть ещё одно ветвление, так как в некоторых системах лидер сессии автоматически получает управляющей терминал.

2019-10-12 02:09 UTC, KotsMikhail commented on nakhatovich.mikhail/lab1/daemon.cpp
> +        terminate_another_instance();
Прежде, чем убивать старого демона, стоит сначала успешно создать нового

2019-10-12 02:09 UTC, KotsMikhail commented on nakhatovich.mikhail/lab1/daemon.cpp
> +            kill(prev, SIGTERM);
Что будет, если послать сигнал несуществующему процессу?

2019-10-12 02:09 UTC, KotsMikhail commented on nakhatovich.mikhail/lab1/daemon.cpp
> +void load_config()
Этот метод явно должен быть инкапсулирован внутри inofity, так как определяет его поведение при инициализации от конфига.

2019-10-12 02:09 UTC, KotsMikhail commented on nakhatovich.mikhail/lab1/inotify.cpp
> +void inotify_t::init()
Почему нельзя делать это в конструкторе?

2019-10-12 02:09 UTC, SWAGLORD1 commented on nakhatovich.mikhail/lab1/inotify.h
> +class inotify_t
По-хорошему, inotify тоже должен быть синглтоном

2019-10-12 02:09 UTC, SWAGLORD1 commented on nakhatovich.mikhail/lab1/inotify.cpp
> +    init();
Ленивая инициализация полезна, если нет гарантии, что объект понадобится. inotify будет гарантированно инициализирован в самом начале программы, если он нужен. И в коде программы он все равно инициализируется вручную.

2019-10-12 04:17 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/build.sh
> +g++ -Wall -Werror types.h utils.h utils.cpp inotify.h inotify.cpp config.h config.cpp daemon.cpp -o daemon
Сделал

2019-10-12 04:18 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/config.h
> +    config_t() = delete;
У меня это не синглтон. Но признаю, что он бы тут не помешал, так что сделаю его.  А данный конструктор я удалил, чтобы проверять корректность пути к файлу с конфигом в фабричном методе.

2019-10-12 04:22 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/daemon.cpp
> +inotify_t inotify;
Как только эти классы перепишутся на синглтоны, то эти переменные не понадобятся.

2019-10-12 04:46 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/daemon.cpp
> +            kill(prev, SIGTERM);
Ничего плохого не должно произойти и можно убрать данную проверку. Но я хотел бы уточнить момент, что будет, если мы попытаемся убить процесс, не являющийся нашим демоном? Стоит ли сделать проверку на то, что мы хотим убить такой же процесс, как и наш. Например, использовать поле Name в /proc/<pid>/status или же ссылку /proc/<pid>/exe?

2019-10-12 04:52 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/inotify.cpp
> +    init();
Это не совсем то. init вызывается в функции main. Дело в том, что функция inotify_init из библиотеки sys/inotify.h может вернуть мне отрицательное значение, что означает ошибку. Поэтому, если не получилось инициализировать, то я каждый раз пытаюсь сделать это заново. 
Но сейчас ещё раз прочитал документацию. И у меня сложилось впечатление, что если уж я получил ошибку, то можно и программу завершить.

2019-10-15 10:32 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/inotify.cpp
> +    init();
Исправлено

2019-10-15 10:33 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/inotify.h
> +class inotify_t
Исправлено

2019-10-15 10:33 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/inotify.cpp
> +void inotify_t::init()
Исправлено

2019-10-15 10:33 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/daemon.cpp
> +void load_config()
Исправлено

2019-10-15 10:33 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/daemon.cpp
> +        terminate_another_instance();
Исправлено

2019-10-15 10:33 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/daemon.cpp
> +    if (setsid() < 0)
Исправлено

2019-10-15 10:33 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/daemon.cpp
> +inotify_t inotify;
Исправлено

2019-10-15 10:33 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/config.h
> +    config_t() = delete;
Исправлено

2019-10-15 23:38 UTC, KotsMikhail requested changes

2019-10-15 23:38 UTC, SWAGLORD1 commented on nakhatovich.mikhail/lab1/daemon.cpp
> +            kill(prev, SIGTERM);
По идее, такую проверку делать стоит, и в настоящих демонах её как правило делают, но эту фичу сложно отлаживать, потому что нельзя создать процесс с определенным pid, и в рамках данной лабораторной я этого требовать не буду. В реальности такая ситуация может возникнуть очень редко, так как linux специально не дает pid недавно завершившихся процессов новым.

2019-10-15 23:38 UTC, SWAGLORD1 commented on nakhatovich.mikhail/lab1/config.cpp
> +config_t * config_t::_instance = NULL;
Почему эта переменная должна быть глобальной?
И лучше использовать nullptr вместо NULL
Тоже самое касается inotify

2019-10-15 23:38 UTC, SWAGLORD1 commented on nakhatovich.mikhail/lab1/daemon.cpp
> +        syslog(LOG_NOTICE, "Soccessfully made fork. Child's pid is %d.", pid);
Опечатка в слове successfully

2019-10-16 10:50 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/daemon.cpp
> +        syslog(LOG_NOTICE, "Soccessfully made fork. Child's pid is %d.", pid);
Исправлено

2019-10-16 11:03 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/config.cpp
> +config_t * config_t::_instance = NULL;
Поменял `NULL` на `nullptr`. 
Данная переменная не глобальная, что можно увидеть по [следующей строчке](https://github.com/MikhailNakhatovich/OS_Labs_SPBPU_2019/blob/nakhatovich.mikhail/nakhatovich.mikhail/lab1/config.h#L26). А в данной строчке происходит инициализация статического поля класса.

2019-10-16 11:05 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab1/daemon.cpp
> +            kill(prev, SIGTERM);
Хорошо. Убрал проверку на существование процесса.

2019-10-17 17:45 UTC, KotsMikhail approved these changes
Засчитано. Можно выбирать следующую

2019-10-17 17:46 UTC, merged