Chepulis.mikhail
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #30
Opened 2019-11-26 16:36 UTC by MChepulis

2019-11-27 23:33 UTC, SWAGLORD1 commented
Не могли бы вы обойтись без включения bits/types/siginfo_t.h? Я извиняюсь, но на моем компе этот заголовочный файл отказывается подключатся, несмотря на то, что библиотека с ним вроде как установлена. Решения из интернета так же не помогли.

2019-11-28 06:44 UTC, MChepulis commented
убрал все bits/types/siginfo_t.h заменив их на signal.h

2019-11-28 07:03 UTC, MChepulis commented
сделал приватным конструктор копирования для синглтон классов

2019-12-01 01:36 UTC, KotsMikhail requested changes
Нет проверки на реальность даты. Дата 99.99.1999 воспринимается как нормальная.
В задании указано, что работу с клиентами следует производить в отдельных потоках. Потоки и процессы - это разные вещи

2019-12-01 01:36 UTC, SWAGLORD1 commented on chepulis.mikhail/lab_2/host/ClientHandler.h
> +    sem_t* semaphore_client;
Эти семафоры нигде не закрываются

2019-12-01 01:36 UTC, SWAGLORD1 commented on chepulis.mikhail/lab_2/host/ClientHandler.h
> +    sem_t* semaphore;
Этот семафор, кажется, нигде не используется

2019-12-01 01:36 UTC, SWAGLORD1 commented on chepulis.mikhail/lab_2/host/Oracle.h
> +class Oracle {
Чем различаются роли этого класса и класса ClientHandler? И почему он у вас синглтон, у вас же может быть несколько клиентов в системе и у вас родственная конфигурация

2019-12-01 01:36 UTC, SWAGLORD1 commented on chepulis.mikhail/lab_2/host/Server.cpp
> +    std::string new_date = "25.11.2019";
Зачем нужна эта константа? Она вроде дальше нигде не используется

2019-12-01 01:36 UTC, SWAGLORD1 commented on chepulis.mikhail/lab_2/host/Server.h
> +    Server(Server& other);
Оператор копирования тоже следует приватить

2019-12-01 06:50 UTC, MChepulis commented on chepulis.mikhail/lab_2/host/Server.cpp
> +    std::string new_date = "25.11.2019";
остатки отладочной информации
убрал инициализацию new_date в строке 97

2019-12-01 08:15 UTC, MChepulis commented on chepulis.mikhail/lab_2/host/Server.h
> +    Server(Server& other);
сделал оператор присваивания тоже приватным

2019-12-01 08:17 UTC, MChepulis commented on chepulis.mikhail/lab_2/host/ClientHandler.h
> +    sem_t* semaphore;
удалил этот семафор, т.к. сейчас он, действительно, уже нигде не используется

2019-12-01 18:31 UTC, MChepulis commented
Добавил проверку реальности вводимой даты
добавил удаление semaphore_host при неудачном создании semaphore_client
Подправил отступы
ClientHandler теперь не синглтон
теперь сервер создаёт потоки для общения с клиентами, а не процессы

2019-12-03 00:17 UTC, KotsMikhail requested changes
Я все ещё не понимаю, почему Oracle и ClientHandler должны быть разными классами. Они реализуют разные части одного и того же объекта и при этом, похоже, сильно пересекаются. В чем различаются их функции и должны ли эти функции быть разнесены по разным классам?

2019-12-03 00:17 UTC, SWAGLORD1 commented on chepulis.mikhail/lab_2/host/Server.cpp
> +void Server::Start() {
Эта функция получилась слишком объемной. Нужно разнести инициализацию и основной цикл. Возможно, перенести инициализацию клиента в конструктор клиента

2019-12-03 00:17 UTC, SWAGLORD1 commented on chepulis.mikhail/lab_2/host/ClientHandler.cpp
> +                syslog(LOG_NOTICE, "KILL KILL KILL KILL KILL KILL KILL");
Я заметил, убирайте)

2019-12-03 06:40 UTC, MChepulis commented on chepulis.mikhail/lab_2/host/ClientHandler.cpp
> +                syslog(LOG_NOTICE, "KILL KILL KILL KILL KILL KILL KILL");
убрал агрессивные надписи в функции ClientHandler::Start()
они были частью отладочной информации

2019-12-03 07:54 UTC, MChepulis commented
убрал ненужный вывод в лог файл
разбил функцию Server::Start() на 4 подфункций
1) void ReadClientCount() - считывает с клавиатуры кол-во клиентов
2) void CreateClient(ClientHandler *handler) - создаёт новый процесс, в котором начинает своб работу клиент
3) void StartHandlerActivity(ClientHandler *handler) - создаёт новый поток, в котором начинает своб работу ClientHandler
4) void Server::Run() - основной цикл работы сервера. Происходит считывание информации от пользователя и её перенаправление в потоки

По поводу ClientHandler и Oracle:
ClientHandler находится на стороне сервера, получает некую информацию от него и отправляет её клиенту и ожидает ответа.При получении выводит результат или же по истечении таймаута закрывается. Если закрывается ClientHandler, то он должен закрыть клиента, за которого отвечает. Также ClientHandler является владельцем всех каналов межпроцессорного взаимодействия и объектов их синхронизации.

Oracle находится на стороне клиента, коим по сути и является.
В его задачи входит открывать уже созданные соединения, и закрывать (не уничтожая) их.
Oracle получает сообщения, обрабатывает их и отправляет результат

2019-12-06 00:11 UTC, KotsMikhail requested changes
Окей, насчет ClientHandler и Oracle вроде понятно, но зачем вы передаете сообщения между основным потоком и дочерними через pipe? Они же в одном процессе и могут обращаться к одним и тем же переменным. Их нужно только синхронизировать, иначе они могут обращаться к разным значениям одной и той же переменной. К тому же, в этом задании можно всё упростить ещё сильнее и создавать потоки при каждом обращении к клиентам. Принципиальный момент в том, чтобы обмен сообщениями с клиентами был асинхронным, поддерживать потоки на все время сеанса на самом деле не обязательно. Это не лучшее решение, так как создание потоков - затратная операция, но в данной задаче это приемлемое решение.

2019-12-06 00:11 UTC, KotsMikhail commented on chepulis.mikhail/lab_2/host/my_functions.h
> +std::string toString(T val) {
Чем вас std::to_string не устраивает?

2019-12-06 00:11 UTC, KotsMikhail commented on chepulis.mikhail/lab_2/host/Server.cpp
> +void* routine(void * arg) {
В реализации модуля не должно быть посторонних функций, если вам нужна вспомогательная функция - сделайте её приватной функцией класса

2019-12-06 11:58 UTC, MChepulis commented on chepulis.mikhail/lab_2/host/Server.cpp
> +void* routine(void * arg) {
перенёс все "сторонние функции" в приватные методы класса

2019-12-06 11:59 UTC, MChepulis commented on chepulis.mikhail/lab_2/host/my_functions.h
> +std::string toString(T val) {
действительно, забыл про этот болей просто вариант, заменил на него

2019-12-06 12:17 UTC, MChepulis commented
перенёс все "сторонние функции" в приватные методы класса
убрал функцию ToString, заменив её на std::to_string

для общения сервера и хендлера использую pipe, по ряду причин:
1) он не требует синхронизации, потому как сервер только пишет в конец, а хендлер только читает с начала
2) позволяет хендлеру не пропускать сообщения
Так, если сервер посылает сообщения со скоростью большей, чем обрабатывает хендлер, то они просто собираются в очередь  и хендлер обработает их позже, но точно обработает (столько, сколько позволит система).
Это означает, что хендлер обработает все запросы от сервера
т.к. мы вводим даты вручную, то переполнить pipe весьма проблематично
3) все хендлеры обработают каждый запрос только 1 раз, т.к. к ним в канал отправляется 1 сообщение
Значит не нужно отдельно хранить и синхронизировать то, какие хендлеры уже считали (для предотвращения повторного считывания уже обработанных данных)
Не нужно реализовывать собственную очередь заданий для хендлеров и синхронизировать её (т.к. тут уже и у сервер удлиняет, хендлер укорачивает очередь -> нужно синхронизировать)

2019-12-07 14:26 UTC, KotsMikhail approved these changes
Окей, в принципе, я засчитаю такое решение, но на будущее имейте в виду - чем меньше синхронизации между потоками - тем лучше. И тем более не стоит использовать в многопоточных программах инструменты для взаимодействия процессов. В частности, pipe буферизует все, что через него пробрасывают, и не дает никаких гарантий на время доставки. Если передавать таким образом большие сообщения, то все может работать медленно. Для таких задач существуют специальные коллекции, например, thread-safe очереди, которые мы будем разбирать в следующей лабе.

2019-12-07 14:27 UTC, merged