Gritsaenko.Nikita lab2
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #31
Opened 2019-12-01 00:08 UTC by Nikitagritsaenko

Lab2, var. 15: single host - single client, ipc: seg, mq, fifo

2019-12-02 00:08 UTC, KotsMikhail requested changes
host_mq вылетает сразу после запуска с сообщением Error: connection failed

2019-12-02 00:08 UTC, KotsMikhail commented on gritsaenko.nikita/lab2/client/client.cpp
> +    std::string proc = "/proc/" + std::to_string(host_pid);
Эту проверку логичнее делать на стороне клиента

2019-12-02 00:08 UTC, KotsMikhail commented on gritsaenko.nikita/lab2/client/client.h
> +    client_t(client_t&) = delete;
Оператор копирования тоже следует приватить или удалять

2019-12-02 00:21 UTC, Nikitagritsaenko commented
> host_mq вылетает сразу после запуска с сообщением Error: connection failed

Вы с sudo запускали? Без sudo у меня host_mq и host_fifo запускаются корректно, а вот host_seg - нет. Если с sudo запускать, то всё должно работать. Тестировал на Linux Mint Cinnamon и Ubuntu 18.04. 

Если проблема не в этом, то сообщите, пожалуйста, что в syslog вывелось...

2019-12-02 00:24 UTC, Nikitagritsaenko commented on gritsaenko.nikita/lab2/client/client.cpp
> +    std::string proc = "/proc/" + std::to_string(host_pid);
Она ведь и есть на стороне клиента?

2019-12-03 23:40 UTC, KotsMikhail requested changes
С sudo все нормально работает, но такого быть не должно. Пользовательские приложения должны корректно работать без прав администратора.

2019-12-03 23:40 UTC, SWAGLORD1 commented on gritsaenko.nikita/lab2/client/client.cpp
> +    std::string proc = "/proc/" + std::to_string(host_pid);
Я имел в виду реализацию клиента, а не main

2019-12-04 20:05 UTC, Nikitagritsaenko commented
@SWAGLORD1, исправил. 
- Оператор копирования приватный и удаленный
- Проверка pid хоста теперь находится в реализации клиента
- Все взаимодействия должны запускаться без прав администратора. Если это не так, то сообщите, пожалуйста, что вывелось в syslog. У меня на Linux Mint и Ubuntu запускается.

2019-12-05 21:11 UTC, KotsMikhail approved these changes
Засчитано

2019-12-05 21:12 UTC, merged