Add Lab 2 implementation
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #32
Opened 2019-12-10 17:51 UTC by pv6

2019-12-12 22:13 UTC, KotsMikhail requested changes
На хосте должно быть ожидание семафора по таймауту

2019-12-12 22:13 UTC, KotsMikhail commented on vasilyev.peter/lab2/interface/conn.h
> +    ss << message << ", errno = " << strerror(errno);
По-идее, это можно делать в обработчике исключения, тогда не придется писать отдельную функцию и писать код ошибки в сообщения исключения

2019-12-12 22:13 UTC, SWAGLORD1 commented on vasilyev.peter/lab2/host/host_class.cpp
> +  static const Command COMMANDS[] = {Command::EXIT, Command::INPUT_DATE};
Почему нельзя просто воспользоваться преобразованием типов?

2019-12-18 16:08 UTC, pv6 commented on vasilyev.peter/lab2/interface/conn.h
> +    ss << message << ", errno = " << strerror(errno);
Перенес в обработчик исключений

2019-12-18 16:09 UTC, pv6 commented on vasilyev.peter/lab2/host/host_class.cpp
> +  static const Command COMMANDS[] = {Command::EXIT, Command::INPUT_DATE};
Согласен, в данном случае можно просто кастовать к енаму, исправил

2019-12-18 16:10 UTC, pv6 commented
Добавил у хоста ожидание семафора по тайм-ауту

2019-12-18 21:51 UTC, KotsMikhail approved these changes
Засчитано

2019-12-18 21:51 UTC, merged