Sergeev.georgii
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #35
Opened 2019-12-13 16:21 UTC by sergeevgk

2019-12-16 00:45 UTC, KotsMikhail requested changes
Ходы волка и козлят должны быть в обратном порядке. Сначала козлята прячутся - потом волк их ловит.
Неадекватное поведение хоста, в случае, если в качестве хода волка ввести строку
Как получилось так, что ваш код процентов на 50 совпадает с кодом Жукова?

2019-12-16 09:15 UTC, sergeevgk commented
Исправил замечания.
Схожесть, наверное, может проявляться в алгоритме работы хоста с клиентами. Было сложно сразу понять, как они должны взаимодействовать по заданию, и тот вариант, который есть сейчас, представляется мне единственно возможным.  Он возник в ходе обсуждения с другими студентами, без списывания.

2019-12-19 00:02 UTC, KotsMikhail requested changes
В дополнение к тому, что я написал, загляните в пул реквест Жукова. У вас есть почти все те же ошибки, что и у него, их следует исправить

2019-12-19 00:02 UTC, KotsMikhail commented on sergeev.georgii/lab2/connections/conn_mq.cpp
> +std::map<int, const char*> names;
Почему нельзя обойтись без глобальных переменных в реализации видов взаимодействий?

2019-12-19 00:02 UTC, KotsMikhail commented on sergeev.georgii/lab2/host/wolf.h
> +    static std::map<conn*, message> goats_messages;
Если у вас в классе куча map ов с разной информацией, то, возможно. эта информация должна быть инкапсулирована где-то ещё. И почему все эти переменные должны быть статическими?

2019-12-19 00:02 UTC, KotsMikhail commented on sergeev.georgii/lab2/interfaces/Message.h
> +enum Status {
Лучше использовать enum class

2019-12-19 00:02 UTC, KotsMikhail commented on sergeev.georgii/lab2/interfaces/connection_info.h
> +struct connection_info
Единственная причина для существования этого класса - передать 3 параметра в конструктор клиента. Это можно сделать просто передав значения

2019-12-19 00:02 UTC, KotsMikhail commented on sergeev.georgii/lab2/host/wolf.cpp
> +        for (auto iter : connections) {
Возможно, распараллеливание обработки клиентов стоит вынести в отдельную функцию, иначе слишком много дублирования кода

2019-12-19 19:50 UTC, sergeevgk commented on sergeev.georgii/lab2/connections/conn_mq.cpp
> +std::map<int, const char*> names;
Эти переменные оставались с прошлых версий, где без них не работала программа. 
Исправил, переменные убраны

2019-12-19 19:52 UTC, sergeevgk commented on sergeev.georgii/lab2/host/wolf.h
> +    static std::map<conn*, message> goats_messages;
Исправил:
Часть информации перенесена в класс клиента. То, что осталось (std::map clients и std::map clients_messages) обязано быть static, потому что используется в методах, передаваемых в pthread_create по указателю, а он не может принимать указатель на не static функции (насколько я понял).

2019-12-19 19:53 UTC, sergeevgk commented on sergeev.georgii/lab2/interfaces/Message.h
> +enum Status {
Исправлено

2019-12-19 19:53 UTC, sergeevgk commented on sergeev.georgii/lab2/interfaces/connection_info.h
> +struct connection_info
Удалил класс, передаю параметры в конструкторе goat

2019-12-19 19:53 UTC, sergeevgk commented on sergeev.georgii/lab2/host/wolf.cpp
> +        for (auto iter : connections) {
Выделил работу с потоками в отдельную функцию

2019-12-19 19:55 UTC, sergeevgk commented
Замечания к моему коду и замечания, которые я увидел к предпоследнему коммиту в ветке alexander.zhukov, исправлены

2019-12-21 18:57 UTC, SWAGLORD1 commented on sergeev.georgii/lab2/host/wolf.h
> +    static std::map<conn*, message> goats_messages;
Может, почитайте про указатели на методы

2019-12-21 18:58 UTC, KotsMikhail requested changes
Дописал Жукову ещё несколько замечаний, большинство из них у вас тоже есть

2019-12-21 19:00 UTC, KotsMikhail requested changes

2019-12-21 19:00 UTC, SWAGLORD1 commented on sergeev.georgii/lab2/host/wolf.h
> +    static constexpr double WOLF_WORK_WINDOW = 1;
Чем constexpr отличается от const, и почему тут должно быть именно первое?

2019-12-21 20:10 UTC, sergeevgk commented on sergeev.georgii/lab2/host/wolf.h
> +    static constexpr double WOLF_WORK_WINDOW = 1;
Я долго искал ответ на вопрос, почему компилятор не даёт инициализировать static сonst double внутри класса. Насколько я понял, такая инициализация работает только для т.н. "integral types" (int, char, short, long, bool). 
constexpr создает объект на этапе компиляции и использует его как константу времени компиляции. Если переменная объявлена с constexpr, то она должна быть не только создана, но и проинициализирована на этапе компиляции, в отличие от const. 
Предыдущую константу тоже можно сделать constexpr, мне почему-то не пришло в голову написать одинаково тут.

2019-12-22 02:30 UTC, sergeevgk commented
Замечания исправлены

2019-12-24 00:36 UTC, SWAGLORD1 commented
Ещё одну утечку памяти вы так и не нашли, можете на неё в пул реквесте Жукова посмотреть. 7 баллов за задачу

2024-01-08 21:57 UTC, closed without merging