Added implementation of sets
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #36
Opened 2019-12-14 22:03 UTC by MikhailNakhatovich

2019-12-16 01:29 UTC, KotsMikhail requested changes
Программа отказывается создавать потоки не в режиме администратора, код ошибки 1
Тест времени для множества с оптимистичной синхронизацией почти всегда зависает
Для тестирования удобнее сделать одинаковое число записей для каждого потока, в текущей реализации тестировать структуры на 100+ потоках не очень удобно

2019-12-16 06:45 UTC, MikhailNakhatovich commented
> Программа отказывается создавать потоки не в режиме администратора, код ошибки 1

Да, нужно запускать с `sudo`.
> Тест времени для множества с оптимистичной синхронизацией почти всегда зависает

Могу сказать лишь то, что у меня он завершается раньше, чем у тонкой синхронизации. Тут, наверное, лучше встретиться лично.
> Для тестирования удобнее сделать одинаковое число записей для каждого потока, в текущей реализации тестировать структуры на 100+ потоках не очень удобно

Сделал одинаковое число записей для тестирования писателей и читателей.

2019-12-16 15:35 UTC, MikhailNakhatovich commented
Вернулся к стандартным настройкам создания потоков. `sudo` не требуется.
Сколько различных тестов не делал, пока что ничего не зависло. Нужно просто долго ждать. Например, на текущем конфигурационном файле для тестов мне пришлось ждать около 14 минут до окончания теста со временем.
Для множества с оптимистичной синхронизацией может не очень хорошо выглядеть то, что происходит при удалении, но это единственный вариант, который показался мне хорошим и при этом оказался рабочим. Вся проблема состоит в том, что при данной синхронизации может происходить проход по удалённым узлам и нужно этого как-то избежать в C++.

2019-12-16 18:07 UTC, KotsMikhail requested changes

2019-12-16 18:07 UTC, KotsMikhail commented on nakhatovich.mikhail/lab3/interfaces/config.h
> +enum size_types_t
Лучше использовать enum class

2019-12-16 18:07 UTC, KotsMikhail commented on nakhatovich.mikhail/lab3/interfaces/node.h
> +class node_t
Классы, не являющиеся частью интерфейса лучше скрывать, например делать их private nested классом

2019-12-16 18:07 UTC, KotsMikhail commented on nakhatovich.mikhail/lab3/interfaces/set_fine.hpp
> +curr->unlock();
Почему это должны быть дефайны, а не обычные функции?

2019-12-16 18:07 UTC, KotsMikhail commented on nakhatovich.mikhail/lab3/interfaces/set.h
> +    set_t() = delete;
Удалять стандартные конструкторы у базовых интерфейсов - не очень хороший стиль. У вас потом из-за этого проблемы с созданием классов-потомков, вам приходится их создавать отдельным статическим методом вместо обычного вызова конструктора

2019-12-16 18:07 UTC, SWAGLORD1 commented on nakhatovich.mikhail/lab3/interfaces/set_optimistic.hpp
> +                _removed.push_back(curr);
Не лучшее решение, так как в ходе использования структуры память, выделенная под удаленные элементы не освобождается. А в чём проблема освободить её прямо здесь?

2019-12-16 20:47 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab3/interfaces/set_optimistic.hpp
> +                _removed.push_back(curr);
[Ссылаюсь на свой предыдущий комментарий](https://github.com/SWAGLORD1/OS_Labs_SPBPU_2019/pull/36#issuecomment-566112757). Проблема множества с оптимистичной синхронизацией в том, что мы можем проходить по удалённым узлам. В книге, на которую дана ссылка в задании, приведён код на языке `Java`. У него есть сборщик мусора, поэтому там не удаляются элементы, если по ним проходят в цикле, и этот проход по ним ни на что не влияет, так как всё равно можно добраться до конца множества. В языке `C++` из-за многопоточности появляется проблема.  Суть оптимистичной оптимизации в том, что сначала идёт проход по всем узлам пока не дойдём до нужного (куда вставить или откуда удалить), а уже затем блокируются узлы, до которых мы дошли. При этом сразу после выполняется валидация - нужно понять действительно ли мы можем достичь данных узлов из начала списка. То есть имеется целых два прохода, при которых мы можем обратиться к памяти, которая может быть освобождена в другом потоке. Поэтому было принято решение просто сохранить узлы в массив и уже потом его очистить. Могу сказать, что я пытался глупым, но судя по всему рабочим способом проверить, не освобождена ли память, к которой я собираюсь обратиться. Но в итоге программа просто зависала в циклах. Другой мой подход был в использовании `shared_ptr`, но он оказался не потокобезопасным, из-за чего выскакивала ошибка `segmentation fault`, как впрочем и в случае обращения к памяти, которая нам не принадлежит.

2019-12-16 20:54 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab3/interfaces/set.h
> +    set_t() = delete;
Я запрещаю кому угодно просто так создавать экземпляр моего класса. Это сделано умышленно. При создании множества, у меня может не выделиться память для головы и хвоста списка. И что мне при этом делать, если я нахожусь уже в конструкторе? Я стараюсь писать не писать программу с исключениями. При этом было бы неплохо, чтобы пользователь просто вызывал одну функцию, не передавая ей ничего того, что он должен знать о реализации. Поэтому я использую одно из решений для таких задач: сделать функцию, внутри которой будут все проверки, и в случае, если всё хорошо, просто передать все данные в множество через специальный конструктор.
Не вижу здесь ничего плохого.

2019-12-16 20:55 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab3/interfaces/set_fine.hpp
> +curr->unlock();
Хотел выиграть немного в скорости, но как оказалось на обычных функциях ничего не изменилось.

2019-12-16 20:57 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab3/interfaces/node.h
> +class node_t
Исправил.

2019-12-16 20:57 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab3/interfaces/config.h
> +enum size_types_t
Исправил.

2019-12-17 14:40 UTC, SWAGLORD1 commented on nakhatovich.mikhail/lab3/interfaces/set_fine.hpp
> +curr->unlock();
Если вы хотите, чтобы компилятор сделал макроподстановку, следует использовать ключевое слово inline, стоит избегать использования директив препроцессора, так как они не проверяются компилятором. Но в данном случае это действительно не должно сильно влиять на производительность

2019-12-17 15:01 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab3/interfaces/set_fine.hpp
> +curr->unlock();
Я знал про `inline`. Просто в моём сознании установилось правило, что при совмещении `inline` и циклов компилятор может проигнорировать слово `inline`. Поэтому использовал директивы препроцессора. Вот такая предыстория.

2019-12-17 15:33 UTC, KotsMikhail commented on nakhatovich.mikhail/lab3/interfaces/set.h
> +    set_t() = delete;
В принципе, я готов согласиться с таким решением, но в чём проблема использовать в конструкторе исключения? Да, они медленные, но конструктор контейнера не предполагается вызывать часто.

2019-12-17 15:33 UTC, SWAGLORD1 commented on nakhatovich.mikhail/lab3/interfaces/set_optimistic.hpp
> +                _removed.push_back(curr);
Хорошее решение в такой ситуации - реализация подсчета ссылок на каждый элемент списка и удаление когда он станет нулевым, это подробно описано в источнике [2] в разделе неблокирующей синхронизации, но, пожалуй, в задаче на 10 баллов я готов засчитать ваше решение

2019-12-17 16:25 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab3/interfaces/set.h
> +    set_t() = delete;
Проблема не в том, что они медленные. Я уже давно привык писать конструкторы, внутри которых я не вызываю исключения. По крайней мере вызов исключения в конструкторе приведёт к тому, что деструктор не будет вызван. Да, я знаю, что стандартные классы из библиотек С++ используют исключения внутри конструкторов. Да, я их не обрабатываю, но это лишь потому, что на моей памяти у меня они ни разу не выскакивали.  Да и к тому же в такой лабораторной вряд ли появятся. 
Возвращаясь к тому, что деструктор не вызовется - да, я могу почистить всю память, что удачно выделил, а потом вызвать исключение и тогда утечек быть не должно, что  по-моему мнению является главной проблемой. Но мне не кажется это хорошей идеей. По-моему лучше не использовать исключения в конструкторах.

2019-12-17 16:26 UTC, MikhailNakhatovich commented on nakhatovich.mikhail/lab3/interfaces/set_optimistic.hpp
> +                _removed.push_back(curr);
Спасибо! Почитаю.

2019-12-17 17:58 UTC, SWAGLORD1 commented on nakhatovich.mikhail/lab3/interfaces/set.h
> +    set_t() = delete;
Окей, засчитаю такое решение, но вообще, именно для таких случаев придумали умные указатели. Рекомендую ими пользоваться.

2019-12-17 17:59 UTC, merged