Tunikov.dmitrii
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #37
Opened 2019-12-15 18:18 UTC by DmitriiTunikov

Здравствуйте. Пока не проходит общий тест при переборе всех возможных вариантов кол-ва читателей и писателей. Остальные тесты прошли. Можете пока код глянуть по идее.

2019-12-16 20:04 UTC, KotsMikhail requested changes
В задании указано, что пользоваться примитивами синхронизации С++ 11 запрещено

2019-12-16 20:11 UTC, DmitriiTunikov commented
@SWAGLORD1 в pthread не atomic переменных. Как тогда вы предлагаете это делать? Я только atomic использую в лабе.

2019-12-17 16:35 UTC, KotsMikhail requested changes

2019-12-17 16:35 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab3/makefile
> +LIBS = -lpthread -latomic
-latomic вроде вам уже не нужен

2019-12-17 16:35 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab3/node/Node.h
> +struct Node {
Желательно скрывать классы, которые относятся к реализации, например делать их private nested классом

2019-12-17 16:35 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab3/stack/Stack.h
> +    static void* writeToStack(void *arg);
Зачем нужны эти две функции? Если только для тестирования, то им нечего делать в интерфейсе класса

2019-12-17 16:35 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab3/lock_free_stack/LockFreeStack.h
> +    }__attribute__((__aligned__(16)));;
Зачем вам здесь выравнивание?

2019-12-17 16:35 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab3/stack/Stack.h
> +enum StackType
Лучше использовать enum class

2019-12-17 16:35 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab3/node/Node.h
> +    std::shared_ptr<int> m_data;
Зачем вам тут умный указатель? Вам все равно приходится удалять узлы вручную

2019-12-17 20:15 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab3/makefile
> +LIBS = -lpthread -latomic
Проект не сбилдится без -latomic. Будет ошибся undefined reference to `__atomic_load_16'. Хотя я нигде не включаю и не использую std::atomic. 
Вообще в данной лабе нужны атомарные операции, и чтобы это ложилось на модель памяти c++11 необходимо использовать либо std::atomic, либо встроенные функции, которые я и использую https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html.
Иначе не понятно, откуда взять атомарные перемернные и операции.
Либо тогда уже писать свою библиотеку для работу с атомарными операциями(очень трудоемкое занятие), но вряд ли в этом суть лабы заключается.

2019-12-17 20:23 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab3/lock_free_stack/LockFreeStack.h
> +    }__attribute__((__aligned__(16)));;
Атомарные функции используют выравнивание для атомарного типа. Поэтому без него здесь не обойтись.

2019-12-17 20:35 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab3/node/Node.h
> +    std::shared_ptr<int> m_data;
Чтобы это соответствовало интерфейсу общему для стека. 
Просто в LockFreeStack нужно именно такой способ использовать, этот способ безопасен относительно исключений, которые могут возникнуть во время копирования при возврате объекта из pop. С типом int проблем не будет. Но в общем случае правильнее использовать  shared_ptr, он не вызывает исключений.
А я со стеком в тестах работаю, как с базовым классом, поэтому и в LockStack сделал shared_ptr, это не проблема в принципе.

2019-12-17 20:39 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab3/node/Node.h
> +struct Node {
@SWAGLORD1 сделал.

2019-12-17 20:39 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab3/stack/Stack.h
> +    static void* writeToStack(void *arg);
@SWAGLORD1 Сделал.

2019-12-17 20:39 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab3/stack/Stack.h
> +enum StackType
Сделал.

2019-12-18 23:35 UTC, KotsMikhail requested changes

2019-12-18 23:35 UTC, SWAGLORD1 commented on tunikov.dmitrii/lab3/lock_stack/LockStack.h
> +        std::shared_ptr<int> m_data;
Это было бы разумно, если бы ваш стек мог хранить произвольные типы данных, но заворачивать int в умный указатель - это все таки немного расточительно, потому что shared_ptr хранит число ссылок и перерасход по памяти получается довольно существенный

2019-12-19 06:43 UTC, DmitriiTunikov commented on tunikov.dmitrii/lab3/lock_stack/LockStack.h
> +        std::shared_ptr<int> m_data;
@SWAGLORD1 убрал shated_ptr.

2019-12-20 01:39 UTC, KotsMikhail approved these changes
Засчитано

2019-12-20 01:39 UTC, merged