Kozlov.ilya
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #38
Opened 2019-12-15 21:12 UTC by ik6cgsg

Версия без сценария "сравнение скорости работы".

2019-12-16 18:18 UTC, ik6cgsg commented
Реализовал все необходимое

2019-12-18 21:11 UTC, KotsMikhail requested changes

2019-12-18 21:11 UTC, KotsMikhail commented on kozlov.ilya/lab3/src/lazy_list/lazy_list.h
> +  LazyList(LazyNode<T>* head, const NodeCollector<LazyNode<T>>& collector);
Очень странный интерфейс конструктора, который фактически заставляет пользователя самостоятельно инициализировать поля класса. Это нарушает принцип инкапсуляции

2019-12-18 21:11 UTC, KotsMikhail commented on kozlov.ilya/lab3/src/lazy_list/lazy_node.h
> +class LazyNode: public Node<T>
Классы реализации следует скрывать, например, делать их private nested классами. Тоже самое касается NodeCollector

2019-12-18 21:11 UTC, KotsMikhail commented on kozlov.ilya/lab3/src/lazy_list/lazy_list.hpp
> +    if (prev->timedLock() != 0)
Зачем вам здесь ожидание с таймаутом? Если вам не отдают замок, вам все равно больше нечего делать, кроме как ждать

2019-12-18 21:11 UTC, KotsMikhail commented on kozlov.ilya/lab3/src/shared/set_creator/set_creator.h
> +class SetCreator
Использовать строителя для создания простой коллекции - это выстрел из пушки по воробьям. Чем вас не устраивает просто использовать конструктор?

2019-12-18 21:11 UTC, KotsMikhail commented on kozlov.ilya/lab3/src/shared/node/node.h
> +  Node(const T& item, int key, pthread_mutex_t& mutex) noexcept;
Почему нельзя создать замок и посчитать ключ внутри конструктора?

2019-12-18 21:11 UTC, KotsMikhail commented on kozlov.ilya/lab3/src/shared/node_creator/node_creator.h
> +class NodeCreator
Почему нельзя создавать узлы просто в конструкторе?

2019-12-18 21:11 UTC, SWAGLORD1 commented on kozlov.ilya/lab3/src/shared/node_collector.h
> +class NodeCollector
Более качественным решением было бы реализовать подсчет ссылок и удалять элементы, на которые никто не ссылается. Но в рамках данной работы я засчитаю ваше решение

2019-12-18 21:11 UTC, SWAGLORD1 commented on kozlov.ilya/lab3/src/lazy_list/lazy_list.hpp
> +        collector.add(curr);
Судя по вашему коду, эта операция может быть неудачной. Более того, в случае большого числа читателей она скорее всего будет неудачной. Что произойдет в таком случае?

2019-12-18 21:42 UTC, SWAGLORD1 commented
Только сейчас заметил, что при увеличении числа записей до 1000, тест зависает не выводя ничего в консоль

2019-12-18 22:10 UTC, ik6cgsg commented on kozlov.ilya/lab3/src/lazy_list/lazy_list.hpp
> +    if (prev->timedLock() != 0)
Я так понял ТЗ, что нужен 1 секундный таймаут на ожидание и вызов pthread_yield()

2019-12-18 22:14 UTC, ik6cgsg commented on kozlov.ilya/lab3/src/lazy_list/lazy_node.h
> +class LazyNode: public Node<T>
Мне кажется, делать разновидность узла его собственным nested подклассом нелогично, поэтому я и использую наследование.

2019-12-18 22:18 UTC, ik6cgsg commented
@SWAGLORD1 по поводу многочисленных строителей. Мне хотелось сделать безопасное создание структур данных и самым очевидным для меня решением было использовать фабрики везде, где могут быть ошибки при создании в конструкторе. Так как создание мьютексов и атрибутов может быть ошибочно, я использую фабрику для узлов. Так как множества создаются через создание 2 dummy узлов, то здесь тоже пришлось использовать фабрику и так далее...

2019-12-19 00:30 UTC, ik6cgsg commented on kozlov.ilya/lab3/src/lazy_list/lazy_list.hpp
> +        collector.add(curr);
Почему она будет неудачной? Каждый читатель ждет, пока ему не освободят mutex, и только потом добавляет в вектор необходимый узел и дальше без проблем отпускает mutex для других ждущих читателей.

2019-12-19 08:12 UTC, ik6cgsg commented
@SWAGLORD1 с такими параметрами
![image](https://user-images.githubusercontent.com/13069335/71155336-8311d980-224e-11ea-9a3f-7d99b6d40590.png)
тесты долго, но постепенно проходятся:
![image](https://user-images.githubusercontent.com/13069335/71155225-565dc200-224e-11ea-8409-1ccfe62fbf86.png)
Долго ничего не выводится из за конструирования тестов и заполнения множества для тестов на читателей. Тестов создается 126 штук при запуске программы... И работаю они не так быстро, исходя из картинки.

2019-12-19 13:37 UTC, ik6cgsg commented
@SWAGLORD1 вынес количество запусков каждого теста в тесте на сравнение в конфиг файл, конструкторы заприватил

2019-12-21 18:32 UTC, KotsMikhail requested changes
Для безопасного создания структур существуют умные указатели. Даже статический фабричный метод вполне подошел бы. Использовать отдельный класс для создания класса с одним параметром - излишнее усложнение. Вы когда-нибудь видели, чтобы кто-нибудь создавал с помощью фабрики обычный std::list? Почему тогда вам кажется, что это хорошее решение для ваших структур?

2019-12-21 18:32 UTC, SWAGLORD1 commented on kozlov.ilya/lab3/src/lazy_list/lazy_list.hpp
> +    if (prev->timedLock() != 0)
Да, но при чем тут ожидание замков? Когда вы ждете pthread_mutex, ваш поток и так не исполняется, это же не спинлок. pthread_yield надо вызывать, если какой-то поток захватил процессор больше, чем на секунду и проверять это надо в при тестировании структуры, а не в её реализации

2019-12-21 18:32 UTC, SWAGLORD1 commented on kozlov.ilya/lab3/src/lazy_list/lazy_list.hpp
> +        collector.add(curr);
Потому что в реализации стоит условие, которое может быть не выполненным, хотя бы в теории, тогда добавление в коллекцию не произойдет и ваша функция вернет false. Я действительно был не прав, когда сказал, что это будет происходить часто, потому что мне показалось, что у вас там trylock. Кстати, в каких случаях pthread_mutex_lock возвращает ошибку?

2019-12-21 18:32 UTC, SWAGLORD1 commented on kozlov.ilya/lab3/src/lazy_list/lazy_node.h
> +class LazyNode: public Node<T>
Это действительно нелогично, и поэтому так делать не надо. Что мешает вам сделать их подклассами соответствующих структур? Это все ещё не помешает вам наследоваться.

2019-12-22 14:05 UTC, ik6cgsg commented
@SWAGLORD1 поправил.
pthread_mutex_lock возвращает ошибку, если приоритет вызывающего потока выше, чем предусмотрен, если передано неверное значение и если слишком много рекурсивных локов

2019-12-24 01:47 UTC, SWAGLORD1 commented
Засчитано

2019-12-24 01:47 UTC, merged

2019-12-24 03:13 UTC, ik6cgsg commented
А почему 5 баллов? Вроде задача была выполнена и код работал до дедлайна вторник, 24 декабря 2019г., 04:47 +03:00 от SWAGLORD1  notifications@github.com :

>Засчитано
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2019-12-24 13:43 UTC, SWAGLORD1 commented
Извиняюсь, моя ошибка, добавил баллов