First version of lab1 (var. 08)
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #4
Opened 2019-10-10 21:11 UTC by Nikitagritsaenko

2019-10-12 13:35 UTC, KotsMikhail requested changes
Программа неадекватно реагирует на пустой конфиг и на несуществующие пути.
Так же не стоит никогда в коде с++ использовать системные вызовы, кроме случаев крайней необходимости, так как они могут работать по разному на разных системах

2019-10-13 19:51 UTC, Nikitagritsaenko commented
> Программа неадекватно реагирует на пустой конфиг и на несуществующие пути.

Исправил

> Так же не стоит никогда в коде с++ использовать системные вызовы, кроме случаев крайней необходимости, так как они могут работать по разному на разных системах

Заменил системные вызовы на c++ функции

2019-10-15 21:35 UTC, KotsMikhail requested changes
Демон всё ещё неадекватно реагирует на несуществующие пути. Вместо завершения работы он каждые 30 секунд спамит сообщения об ошибках и продолжает пытаться работать. Причем спамит не в системный лог а прямо в консоль.

2019-10-15 21:54 UTC, Nikitagritsaenko commented
@SWAGLORD1
Михаил, так его убивать в таком случае надо? Может, он перечитает конфиг, который во время работы демона исправили (подсунули правильные пути), и после этого будет работать дальше. Я думал, это так должно быть.

Я тогда вот так переделаю:
1. Во время чтения конфиг-файла проверю корректность путей. Не буду создавать демона в таком случае
2. Спамить буду в консоль, чтобы пользователь увидел, что конфиг надо поправить, и тогда демон будет запущен. 

Правильно?

2019-10-16 19:17 UTC, Nikitagritsaenko commented
@SWAGLORD1 
В общем я сделал так, как описал выше. 
+ демон теперь завершает работу, если конфиг изменяется на некорректный, а затем демону присылается SIGHUP

2019-10-17 18:05 UTC, KotsMikhail requested changes
Извиняюсь за поздний ответ.
Решение, которое вы описали, меня в принципе устраивает. Но теперь ваш демон, судя по логам, получает sigterm сразу после старта при запуске с любым корректным конфигом.

2019-10-17 19:10 UTC, Nikitagritsaenko commented
@SWAGLORD1, Исправил.

Дело в том, что когда я тестировал, в pid-файле всегда был pid какого-то процесса (ранее созданного демона). В данном случае никаких демонов не было создано, поэтому вызывалась функция kill с нулевым pid и сигналом SIGTERM. Как я понял, в таком случае SIGTERM присылается всем процессам той группы, в которой находится отправитель. Таким образом, после создания нового демона, убивался он же, а не предыдущий демон (которого и не было в этом случае).

2019-10-21 02:44 UTC, KotsMikhail requested changes
Если запустить демона с любым корректным конфигом, а затем убрать из конфига интервал и послать демону sighup, то демон продолжит работу, судя по всему, со старым конфигом. Все остальные тесты вроде корректно работают

2019-10-21 02:44 UTC, SWAGLORD1 commented on gritsaenko.nikita/lab1/lab1.cpp
> +        printf("Error: exprected 2 arguments, got %d", argc);
Перевод строки после сообщения об ошибке в консоли

2019-10-21 02:44 UTC, SWAGLORD1 commented on gritsaenko.nikita/lab1/lab1.cpp
> +        printf("Source directory %s is not exist. Copy failed. \n", src.c_str());
does not exist
В других сообщениях такая же ошибка

2019-10-21 02:44 UTC, SWAGLORD1 commented on gritsaenko.nikita/lab1/lab1.cpp
> +       printf("Unable to create directory %s \n", path.c_str());
Ошибки в процессе работы демона должны выводится в syslog, а не в консоль

2019-10-21 02:44 UTC, SWAGLORD1 commented on gritsaenko.nikita/lab1/lab1.cpp
> +namespace patch {
Разные пространства имен должны быть в разных файлах

2019-10-21 02:44 UTC, SWAGLORD1 commented on gritsaenko.nikita/lab1/lab1.cpp
> +    template < typename T > std::string to_string( const T& n ) {
чем вас std::to_string не устраивает?

2019-10-21 02:44 UTC, SWAGLORD1 commented on gritsaenko.nikita/lab1/lab1.cpp
> +        if (read_config_file() != EXIT_SUCCESS) {
Тут должно быть сообщение об ошибке в логе

2019-10-21 12:07 UTC, Nikitagritsaenko commented on gritsaenko.nikita/lab1/lab1.cpp
> +    template < typename T > std::string to_string( const T& n ) {
Компилятор ругался на std::to_string. 
Теперь я эту функцию вообще не использую, так что удалил namespace.

2019-10-21 12:07 UTC, Nikitagritsaenko commented on gritsaenko.nikita/lab1/lab1.cpp
> +namespace patch {
Удалил namespace, ибо он больше не нужен

2019-10-21 12:07 UTC, Nikitagritsaenko commented on gritsaenko.nikita/lab1/lab1.cpp
> +       printf("Unable to create directory %s \n", path.c_str());
Исправил

2019-10-21 12:08 UTC, Nikitagritsaenko commented on gritsaenko.nikita/lab1/lab1.cpp
> +        printf("Source directory %s is not exist. Copy failed. \n", src.c_str());
Исправил

2019-10-21 12:08 UTC, Nikitagritsaenko commented on gritsaenko.nikita/lab1/lab1.cpp
> +        printf("Error: exprected 2 arguments, got %d", argc);
Исправил

2019-10-21 12:08 UTC, Nikitagritsaenko commented on gritsaenko.nikita/lab1/lab1.cpp
> +        if (read_config_file() != EXIT_SUCCESS) {
Исправил

2019-10-21 12:15 UTC, Nikitagritsaenko commented
> Если запустить демона с любым корректным конфигом, а затем убрать из конфига интервал и послать демону sighup, то демон продолжит работу, судя по всему, со старым конфигом. Все остальные тесты вроде корректно работают

@SWAGLORD1, исправил. Теперь демон в таком случае не продолжает работу, т.к. конфиг некорректный.

2019-10-22 00:47 UTC, KotsMikhail approved these changes
Засчитано

2019-10-22 00:48 UTC, merged