Added lab3
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #40
Opened 2019-12-18 23:40 UTC by MaximSmolskiy

2019-12-20 01:10 UTC, KotsMikhail requested changes

2019-12-20 01:10 UTC, KotsMikhail commented on smolskiy.maxim/lab3/int/fine_list.hpp
> +    while (curr->key < key)
Проход по списку лучше вынести в отдельную функцию

2019-12-20 01:10 UTC, KotsMikhail commented on smolskiy.maxim/lab3/tests/tests.h
> +enum class SetType
Лучше использовать enum class

2019-12-20 01:10 UTC, KotsMikhail commented on smolskiy.maxim/lab3/tests/tests.h
> +void RunTestWriters(SetType setType, DataType dataType, int numberWriters, int numberRecords, int numberTimes);
Было бы лучше, если все это поместить в классе или numspace

2019-12-20 05:35 UTC, MaximSmolskiy commented on smolskiy.maxim/lab3/tests/tests.h
> +enum class SetType
Тут и использован enum class. DataType тоже enum class.

2019-12-20 06:17 UTC, MaximSmolskiy commented
Исправил

2019-12-21 19:31 UTC, KotsMikhail approved these changes
Засчитано

2019-12-21 19:31 UTC, merged