Surikov.ilya
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #42
Opened 2019-12-20 01:58 UTC by Chopikov

2019-12-21 19:12 UTC, KotsMikhail reviewed
Какие аргументы принимает на вход ваша программа?

2019-12-21 19:42 UTC, Chopikov commented
Прощу прощения, забыл это указать
5 аргументов, в следующем порядке: 
WRITERS_NUM
READERS_NUM
THREADS_WRITERS 
THREADS_READERS
TIME_ITERATIONS

2019-12-22 13:02 UTC, KotsMikhail requested changes
Запустил тесты со следующими параметрами:
./set 1000 1000 10 10 100
Получил следующий вывод:
10
---------------Tests for SetOptimistic--------------------------
Readers tests:
Segmentation fault

2019-12-22 20:02 UTC, Chopikov commented
Исправил

2019-12-24 01:05 UTC, SWAGLORD1 commented
Засчитано

2019-12-24 01:05 UTC, merged