First lab task 5
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #46
Opened 2020-02-03 14:01 UTC by decentNick

2020-02-03 17:26 UTC, KotsMikhail requested changes
В задании указано, что временной интервал должен указываться в конфигурационном файле, у вас он фиксированный

2020-02-15 22:23 UTC, KotsMikhail requested changes
Разные классы должны быть в разном файле, при этом объявление класса должно быть в заголовочном файле, а реализация - в файле cpp
Неодинаковый стиль отступов фигурных скобок

2020-02-15 22:23 UTC, KotsMikhail commented on kononov.pavel/lab1/daemon_source.cpp
> +struct ConfigReader {
Не стоит использовать структуры в C++, они поддерживаются языком только для обратной совместимости с Си

2020-02-15 22:23 UTC, KotsMikhail commented on kononov.pavel/lab1/daemon_source.cpp
> +} config_reader;
Зачем здесь создавать экземпляр класса, который вы, к тому же, нигде не используете?

2020-02-15 22:23 UTC, SWAGLORD1 commented on kononov.pavel/lab1/daemon_source.cpp
> +#define PID_LOGS "/var/run/daemon_lab_5.pid"
Вместо директив препроцессора лучше использовать static const

2020-03-11 22:39 UTC, KotsMikhail requested changes
Я не помню, чтобы я засчитал вам первую задачу, так что вторую пока что сдавать нельзя. Кроме того, она должна быть отдельным пул реквестом. Кроме того, вы ещё не сообщили мне вариант 2-ой лабораторной, который вы выбрали

2020-04-17 13:52 UTC, decentNick commented
Все изменения исправлены. Уже готов прислать готовую вторую лабораторную. Выбрал 10 вариант.

2020-04-19 04:17 UTC, KotsMikhail requested changes
С отступами фигурных скобок всё ещё проблемы

2020-04-24 14:48 UTC, SWAGLORD1 commented
Засчитано

2020-04-24 14:48 UTC, merged