Lab2 Lavrichenko Olga #22
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #47
Opened 2020-04-17 14:25 UTC by OLavrik

Added realisation lab№2 (12 variant).

2020-04-21 14:14 UTC, KotsMikhail requested changes
Если вы хотите баллы за 2-ую лабораторную, то вам следует выбрать другой уникальный вариант и сделать его полностью самостоятельно

2020-04-21 21:30 UTC, OLavrik commented
Можете пояснить, пожалуйста, что вы имеете ввиду, у меня не укладывается в голове как не самостоятельно можно сделать уникальный вариант? Ведь никто 12 вариант не делал. Заранее спасибо за ответ.

2020-04-22 00:58 UTC, KotsMikhail requested changes

2020-04-22 00:58 UTC, SWAGLORD1 commented on lavrichenko.olga/lab2/conn/conn_fifo.cpp
> +//
Вот так

2020-04-22 00:58 UTC, SWAGLORD1 commented on lavrichenko.olga/lab2/conn/conn_mq.cpp
> +//
И вот так

2020-04-22 00:58 UTC, SWAGLORD1 commented on lavrichenko.olga/lab2/host/host.cpp
> +//
И ещё вот так
Некоторые другие модули так же совпадают с кодом Петра Васильева практически на 100%, за исключением удаленных комментариев

2020-05-06 05:42 UTC, KotsMikhail reviewed
Засчитано

2020-05-06 05:42 UTC, merged