Kozlov.ilya
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #5
Opened 2019-10-11 15:13 UTC by ik6cgsg

2019-10-12 14:50 UTC, KotsMikhail requested changes
При попытке внести любое изменение в конфиг файл демон не запускается с сообщением: CONFIG ERROR: words are. У вас тоже самое, или эта проблема только на моей системе?

2019-10-12 16:18 UTC, ik6cgsg commented
Странно, я писал на Ubuntu 19.04 и такого у меня не было. А без изменений запускается?

2019-10-12 18:51 UTC, SWAGLORD1 commented
Как ни странно, да. Я думал, что проблема в кодировках, но сохранение в
разных кодировках не решило проблему. Возможно ли посмотреть работу на
вашем ноутбуке в часы занятия?

сб, 12 окт. 2019 г. в 19:18, Ilya Kozlov <notifications@github.com>:

> Странно, я писал на Ubuntu 19.04 и такого у меня не было. А без изменений
> запускается?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/SWAGLORD1/OS_Labs_SPBPU_2019/pull/5?email_source=notifications&email_token=AFIJUYSZR75R5NVWUDROZUDQOH2FDA5CNFSM4I73CSJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBCC6SQ#issuecomment-541339466>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFIJUYTYCHML4ULEVMD4LX3QOH2FDANCNFSM4I73CSJA>
> .
>

2019-10-13 15:51 UTC, ik6cgsg commented
Делал не на ноутбуке, а к ПК доступа не было, установил на ноут linux mint виртуальный и тоже не работает, пока буду думать в чем проблема. Реквест закрывать или он остается открытым?

2019-10-13 21:21 UTC, SWAGLORD1 commented
Реквест стоит оставить открытым, если измените что-нибудь в коде своей
программы - то можно в него же добавить изменения.

вс, 13 окт. 2019 г. в 18:51, Ilya Kozlov <notifications@github.com>:

> Делал не на ноутбуке, а к ПК доступа не было, установил на ноут linux mint
> виртуальный и тоже не работает, пока буду думать в чем проблема. Реквест
> закрывать или он остается открытым?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/SWAGLORD1/OS_Labs_SPBPU_2019/pull/5?email_source=notifications&email_token=AFIJUYVJL2MT5WEHLLWCGGLQOM7YPA5CNFSM4I73CSJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBCZE7Q#issuecomment-541430398>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFIJUYTWKQLKMSC7RGW6WB3QOM7YPANCNFSM4I73CSJA>
> .
>

2019-10-14 08:12 UTC, ik6cgsg commented
Поправил, ошибка была связана с пустой строчкой в конце файла.

2019-10-21 01:44 UTC, KotsMikhail requested changes
При попытке создать pid file в /var/run/daemon.pid программа завершилась с ошибкой о некорректном пути
В целом, записывать путь к pid file в конфиге - плохая идея. Если пользователь изменит этот путь и перезапустит демона, то старый демон не завершится. В рамках данной работы его можно захардкодить. Если хотите сделать его настраиваемым - сделайте его параметром сборки.

2019-10-21 01:44 UTC, SWAGLORD1 commented on kozlov.ilya/lab1/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.10)
На более старых версиях cmake ваша программа не соберется?

2019-10-21 01:44 UTC, SWAGLORD1 commented on kozlov.ilya/lab1/daemon.cc
> +  setsid();
Эта и следующая операция в теории могут завершиться неудачно и это нужно проверять и выводить сообщения об ошибках

2019-10-21 01:44 UTC, SWAGLORD1 commented on kozlov.ilya/lab1/daemon.cc
> +    if (stat(path_to_daemon.c_str(), &sb) == 0)
Что будет, если послать сигнал несуществующему процессу?

2019-10-21 01:44 UTC, SWAGLORD1 commented on kozlov.ilya/lab1/daemon.cc
> +  setsid();
После создания сессии нужно создать ещё один дочерний процесс, так как в некоторых системах лидер сессии автоматически получает управляющий терминал

2019-10-21 08:21 UTC, ik6cgsg commented on kozlov.ilya/lab1/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.10)
Соберется, просто не знал насколько старую версию надо указывать

2019-10-21 08:34 UTC, ik6cgsg commented on kozlov.ilya/lab1/daemon.cc
> +    if (stat(path_to_daemon.c_str(), &sb) == 0)
Метод kill вернет ошибку, ничего страшного не произойдет, просто в ТЗ было указано проверять в /proc

2019-10-21 14:39 UTC, ik6cgsg commented
Поправил

2019-10-22 01:40 UTC, KotsMikhail approved these changes
Засчитано

2019-10-22 01:40 UTC, merged