Kononov.pavel Lab2
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #50
Opened 2020-04-24 17:48 UTC by decentNick

Вторая лабораторная 10 вариант. Вместо программных каналов сделал очереди сообщении, потому как в задании надо использовать отдельный поток для каждого клиента. Так же в аргументах хоста требуется указать количество клиентов, тк иначе не понятно в какой момент можно начинать игру (ведь все клиенты должны получать одинаковые числа хоста).

2020-04-25 04:41 UTC, KotsMikhail requested changes
Ваши варианты реализации взаимодействия приняты, в задании ошибка, в вашем варианте действительно нельзя использовать pipe
Ходы козлят должны происходить до хода волка
Неодинаковый стиль наименования полей классов
Уберите исполняемые файлы из пул реквеста

2020-04-25 04:41 UTC, KotsMikhail commented on kononov.pavel/lab2/utils/utils.h
> +const int TIMEOUT = 5;
static const

2020-04-25 04:41 UTC, KotsMikhail commented on kononov.pavel/lab2/interfaces/member.h
> +class Member
Этот класс нигде не используется

2020-04-25 04:41 UTC, KotsMikhail commented on kononov.pavel/lab2/host/wolf.h
> +    Wolf(const Wolf &) = delete;
Зачем удалять конструктор копирования 2 раза?

2020-04-25 04:41 UTC, KotsMikhail commented on kononov.pavel/lab2/host/wolf.h
> +    static ClientInfo *client_info;
Почему все эти поля и функции должны быть статическими?

2020-04-25 04:41 UTC, KotsMikhail commented on kononov.pavel/lab2/host/wolf.cpp
> +    attr = (pthread_attr_t *) malloc(n * sizeof(pthread_attr_t));
new

2020-04-25 04:41 UTC, SWAGLORD1 commented on kononov.pavel/lab2/host/wolf.cpp
> +    static Wolf instance(n);
Такая реализация синглтона приведет к неожиданному поведению, если в программе запросить экземпляр с разными значениями параметра. Какой вообще вы вкладываете смысл в параметр функции, которая должна возвращать ссылку на ваш синглтон?

2020-04-25 04:41 UTC, SWAGLORD1 commented on kononov.pavel/lab2/host/wolf.h
> +    static pthread_t *threads;
Используйте стандартные коллекции вместо указателей на память когда это возможно

2020-04-25 04:41 UTC, SWAGLORD1 commented on kononov.pavel/lab2/host/wolf.cpp
> +    exit(signum);
Всё это не произойдет в случае некорректного завершения работы

2020-04-25 04:41 UTC, SWAGLORD1 commented on kononov.pavel/lab2/host/identifier.h
> +class Identifier {
Зачем нужен этот класс?

2020-04-25 04:41 UTC, SWAGLORD1 commented on kononov.pavel/lab2/client/goat.h
> +class Goat {
Зачем делать этот класс синглтоном?

2020-04-25 04:41 UTC, SWAGLORD1 commented on kononov.pavel/lab2/client/goat.cpp
> +    alarm(5);
Зачем здесь это?

2020-04-25 08:07 UTC, decentNick commented on kononov.pavel/lab2/host/wolf.h
> +    static ClientInfo *client_info;
Они используются в функции ThreadRun, которая должна быть статической. Я пытался сделать иначе, но это самый оптимальный способ на мой взгляд

2020-04-25 08:09 UTC, decentNick commented on kononov.pavel/lab2/client/goat.cpp
> +    alarm(5);
для того, чтобы программа завершалась, если пользователь ошибся пидом

2020-04-25 08:10 UTC, decentNick commented on kononov.pavel/lab2/host/identifier.h
> +class Identifier {
Предполагалось больше функций, на данный момент он действительно не очень важен

2020-04-25 15:16 UTC, KotsMikhail requested changes

2020-04-25 15:16 UTC, SWAGLORD1 commented on kononov.pavel/lab2/host/wolf.h
> +    static ClientInfo *client_info;
Использовать кучу статических переменных никогда не является самым оптимальным способом. Зачем вы тогда пытались сделать из этого класса синглтон?

2020-04-27 05:11 UTC, decentNick commented
Все подправил, только не совсем понятно что значит "Ходы козлят должны происходить до хода волка". Вроде у меня так и есть. Я немного поменял вывод, чтобы все было нагляднее.

2020-04-28 20:36 UTC, KotsMikhail requested changes

2020-04-28 20:36 UTC, KotsMikhail commented on kononov.pavel/lab2/host/wolf.h
> +    int GetClientId();
Зачем нужна эта функция?

2020-04-28 20:36 UTC, KotsMikhail commented on kononov.pavel/lab2/host/wolf.cpp
> +    static Wolf &instance = GetInstance();
Почему эта переменная должна быть статической?

2020-04-28 20:36 UTC, SWAGLORD1 commented on kononov.pavel/lab2/host/client_info.h
> +struct ClientInfo {
Структуры можно использовать для классов-контейнеров, вроде Message, но не для классов, которые реализуют сложное поведение. Реализацию этого класса нужно скрыть

2020-04-28 20:36 UTC, SWAGLORD1 commented on kononov.pavel/lab2/host/wolf.h
> +    static Message Step(Message &msg, ClientInfo &info);
Почему эта функция должна быть статической?

2020-04-28 20:36 UTC, SWAGLORD1 commented on kononov.pavel/lab2/utils/utils.h
> +#define SEMAPHORE_CLIENT_NAME "LAB2_CLIENT"
static const

2020-04-29 09:37 UTC, decentNick commented on kononov.pavel/lab2/host/wolf.h
> +    int GetClientId();
GetClientId - каждому клиенту назначает id. Вынес как функцию, потому что в будущем она может быть не будет изменена.
Step - обработка сообщения, полученного от клиента

2020-04-29 09:38 UTC, decentNick commented on kononov.pavel/lab2/host/wolf.cpp
> +    static Wolf &instance = GetInstance();
не должна быть

2020-04-29 09:39 UTC, decentNick commented on kononov.pavel/lab2/host/wolf.h
> +    static Message Step(Message &msg, ClientInfo &info);
не должна быть

2020-05-01 03:37 UTC, KotsMikhail reviewed
Засчитано

2020-05-01 03:37 UTC, merged