Added lab1
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #7
Opened 2019-10-11 21:10 UTC by MaximSmolskiy

2019-10-14 23:20 UTC, KotsMikhail requested changes
Программа выдает segmentation fault если запустить её без параметров
Программа неадекватно реагирует на конфиг, в котором не указан временной интервал
Непостоянный стиль наименования функций

2019-10-17 09:19 UTC, MaximSmolskiy commented
Исправил

2019-10-21 02:21 UTC, KotsMikhail requested changes
Ваша программа правильно работает, но с кодом есть проблемы. Основная проблема - вы смешиваете стили кодирования на С и С++. Определитесь, на каком языке вы хотите это написать. Исправите - зачту.

2019-10-21 02:21 UTC, SWAGLORD1 commented on smolskiy.maxim/lab1/main.cpp
> +struct Config
Не стоит использовать структуры в с++ коде

2019-10-21 02:21 UTC, SWAGLORD1 commented on smolskiy.maxim/lab1/main.cpp
> +Config cfg;
Почему эта переменная должна быть глобальной?

2019-10-21 02:21 UTC, SWAGLORD1 commented on smolskiy.maxim/lab1/main.cpp
> +    const string ABS_PID_PATH = "/var/run/daemon.pid";
Объявлять константы в середине программы - плохой стиль

2019-10-21 02:21 UTC, SWAGLORD1 commented on smolskiy.maxim/lab1/main.cpp
> +void ProtectAgainstRestart()
Почему конфиг инкапсулирован в отдельный класс, а поведение демона - нет?

2019-10-23 19:16 UTC, MaximSmolskiy commented
Исправил - конфиг сделал Singleton-ом и поведение демона инкапсулировал

2019-10-25 00:34 UTC, KotsMikhail requested changes

2019-10-25 00:34 UTC, KotsMikhail commented on smolskiy.maxim/lab1/config.h
> +    int interval;
Публичные поля в классе. На курсе по с++ вам должны были рассказывать, почему это плохо

2019-10-25 00:34 UTC, KotsMikhail commented on smolskiy.maxim/lab1/config.cpp
> +    static Config instance(cfgName);
В таком решении каждый вызов GetInstance будет создавать новый экземпляр конфига, которые будут удалены только при завершении программы.

2019-10-25 00:34 UTC, SWAGLORD1 commented on smolskiy.maxim/lab1/daemon.cpp
> +        cfg.ReadConfig();
Зачем? Вы же вызываете ReadConfig в GetInstance

2019-10-25 00:34 UTC, SWAGLORD1 commented on smolskiy.maxim/lab1/config.h
> +    void ReadConfig();
Эта функция случайно не должна быть приватной?

2019-10-25 19:14 UTC, MaximSmolskiy commented on smolskiy.maxim/lab1/config.cpp
> +    static Config instance(cfgName);
Это Singleton Майерса (возможно, вы не заметили в этой строчке ключевое слово "static"). instance создастся только один раз (при первом вызове), а при последующих конструктор вызываться не будет, а сразу будет возвращаться instance. Соответственно, такого поведения, как Вы написали, точно не будет (Вы можете убедиться в этом самостоятельно - если бы было такое поведение, то при вызове GetInstance всегда бы вызывался конструктор Config, а внутри него метод ReadConfig и в любом случае какое-то сообщение писалось бы в лог (либо сообщение об ошибке, либо сообщение о том, что конфиг прочитан) - GetInstance вызывается в цикле while (true) (в Daemon::DeleteAllSubfolders) каждые interval секунд - значит в лог бы писалось каждые interval секунд какое-то сообщение - но этого не происходит).

2019-10-25 19:14 UTC, MaximSmolskiy commented on smolskiy.maxim/lab1/daemon.cpp
> +        cfg.ReadConfig();
Соответственно, ReadConfig в GetInstance вызывается только при первом вызове и здесь это нужно.

2019-10-25 19:15 UTC, MaximSmolskiy commented on smolskiy.maxim/lab1/config.h
> +    void ReadConfig();
Соответственно, эта функция должна быть публичной, чтобы я мог её вызвать при обработке сигнала SIGHUP.

2019-10-25 19:40 UTC, MaximSmolskiy commented
Исправил - сделал поля приватным и добавил getter-ы

2019-10-26 14:53 UTC, KotsMikhail approved these changes
Я действительно неправильно прочитал ваш код, я извиняюсь. Сейчас все нормально, задача засчитана

2019-10-26 14:54 UTC, merged