Add daemon
SWAGLORD1/OS_Labs_SPBPU_2019 pull request #8
Opened 2019-10-12 17:33 UTC by dimaaa1fed

2019-10-14 23:55 UTC, KotsMikhail requested changes
Не очевидное сообщение об ошибке в случае пустого конфига или несуществующих путей: daemon_lab: Something goes wrong while creating directory. Так же у вас неодинаковый стиль отступов для фигурных скобок. В остальном все неплохо, кроме замечаний по коду.

2019-10-14 23:55 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab1/build.sh
> +g++ -Wall -Werror main.cpp -o daemon
Если вы используете 11 стандарт С++ то при сборке следует указывать флаг -std=c++11, без него на некоторых системах и версиях компилятора собираться не будет

2019-10-14 23:55 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab1/main.cpp
> +   if ((dir = opendir(pidFolder.c_str())) != NULL) {
Что будет если послать сигнал несуществующему процессу?

2019-10-14 23:55 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab1/main.cpp
> +   setsid();
Создание сессии в теории может быть не успешным

2019-10-14 23:55 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab1/main.cpp
> +   setsid();
Тут должно быть ещё одно ветвление, так как в некоторых системах лидер сессии автоматически получает управляющей терминал.

2019-10-14 23:55 UTC, SWAGLORD1 commented on fedorov.dmitrii/lab1/main.cpp
> +   chdir("/");
Смена директории тоже может пройти неудачно

2019-10-22 07:05 UTC, dimaaa1fed commented on fedorov.dmitrii/lab1/main.cpp
> +   if ((dir = opendir(pidFolder.c_str())) != NULL) {
@SWAGLORD1 Ничего, kill вернет ошибку

2019-10-22 07:07 UTC, dimaaa1fed commented on fedorov.dmitrii/lab1/build.sh
> +g++ -Wall -Werror main.cpp -o daemon
@SWAGLORD1 Используемый мной компилятор не знает про этот флаг, использую аналогичный для более старых -std=c++0x, к следующей лабораторной обновлю версию компилятора

2019-10-23 00:31 UTC, KotsMikhail requested changes
Если послать демону sighup с некорректным конфигом, то он его проигнорирует без каких либо сообщений об ошибке
Стиль кодирования все ещё не в порядке, разный стиль отступов фигурных скобок для функций и остальных операторов и отступы операторов в некоторых местах неадекватные

2019-10-24 22:01 UTC, KotsMikhail requested changes
Заметил, что если в конфиге указать два одинаковых пути, то программа удалит все файлы в этой папке
Со стилем кодирования всё ещё не все в порядке

2019-10-24 22:01 UTC, KotsMikhail commented on fedorov.dmitrii/lab1/main.cpp
> +	 break;
Все ещё проблемы с отступами

2019-10-24 22:01 UTC, KotsMikhail commented on fedorov.dmitrii/lab1/main.cpp
> + 	 string pidFilePath = WORK_DIR + "/" + PID_FILENAME;
И тут

2019-10-24 22:01 UTC, KotsMikhail commented on fedorov.dmitrii/lab1/main.cpp
> +	 unlink(pidFilePath.c_str());
И тут

2019-10-24 22:01 UTC, KotsMikhail commented on fedorov.dmitrii/lab1/main.cpp
> +	 exit(SIGTERM);
Неужели это не заметно?

2019-10-25 16:26 UTC, dimaaa1fed commented on fedorov.dmitrii/lab1/main.cpp
> +	 exit(SIGTERM);
По привычке табуляцию использовал, gedit и сайт git'a на моем ноутбуке отображал, что все ровно

2019-10-25 16:56 UTC, dimaaa1fed commented on fedorov.dmitrii/lab1/main.cpp
> +	 exit(SIGTERM);
По поводу одинаковых путей в конфиге: в задании написано "Копировать содержимое папки 1 в папку 2(предварительно очищая содержимое папки 2)", что ведет к удалению всех файлов, до копирования

Сейчас будет работать так: "Копировать содержимое папки 1 в папку 2(предварительно очищая содержимое папки 2/IMG, 2/OTHERS)"
Сойдет?

2019-10-26 15:02 UTC, KotsMikhail approved these changes
В принципе, меня бы устроило, если бы вы просто запретили одинаковые пути в конфиге, но ваше решение тоже подходит. Задача засчитана.

2019-10-26 15:03 UTC, merged